import { Router } from "express";
import {
  registerUser,
  loginUser,
  logoutUser,
  refreshAccessToken,
  changeCurrentPassword,
  getCurrentUser,
  updateUser,
  updateAvatar,
  updateCoverImage,
  testFunction,
} from "../controllers/user.controller.js";
import { upload } from "../middleware/multer.middleware.js";
import { jwtVerify } from "../middleware/auth.middleware.js";

const router = Router();

router.route("/register").post(
  upload.fields([
    {
      name: "avatar",
      maxCount: 1,
    },
    {
      name: "coverImage",
      maxCount: 1,
    },
  ]),
  registerUser
);

router.route("/test").get(testFunction);
router.route("/login").post(loginUser);
router.route("/refresh-token").post(refreshAccessToken);

// Secured routes
router.route("/logout").post(jwtVerify, logoutUser);
router.route("/change-password").post(jwtVerify, changeCurrentPassword);
router.route("/user").get(jwtVerify, getCurrentUser);
router.route("/user").patch(jwtVerify, updateUser);
router.route("/avatar").patch(jwtVerify, upload.single("avatar"), updateAvatar);
router.route("/cover-image").patch(jwtVerify, upload.single("coverImage"), updateCoverImage);

const addresses = [
  "Suite 116, Musgrave Park, 18 Musgrave Road,MusgraveKwaZulu-Natal",
  "94 Pretorius Street, Mokopane,Limpopo",
  "Suite 112, Musgrave Park,18 Musgrave RoadDurban",
  "12 Wilderness Rd, Claremont,Cape TownWestern Cape",
  "Unit 1, Harry Goemans Centre, 151 Main Road,Bergvliet",
  "200 Rivonia Road MorningsideSandtonGauteng",
  "52 Olivia Rd, Eveleigh,BoksburgGauteng",
  "234 Athol Street, Highlands North,JohannesburgGauteng",
  "665 Mabel Street, Garsfontein,PretoriaGauteng",
  "Vat No: 4530152836, Office 66 Davenport Square,89 Helen Joseph RoadBulwer",
  "21 Postma Street, Secunda,SecundaMpumalanga",
  "10 Prinsman Place, Schoeman Street,PretoriaGauteng",
  "Shop 23 Corner De Clerq 7 Voortrekker Street,Lydenburg (Downtown Centre)Mpumalanga",
  "Enamel Clinic, 3rd Floor, De Waterkant Centre, 9 Somerset Road, Green Point,Cape TownWestern Cape",
  "8th Avenue, Summerstrand,Summerstrand VillageGqeberha",
  "School of Oral Health, Molotlegi St, Ga-Rankuwa, Zone 1,Ga-RankuwaPretoria Gauteng",
  "143 Gerhard Street, Lyttelton,CenturionGauteng",
  "4 Sir Lowry's Pass Rd, Mountainside,Cape TownWestern Cape",
  "32 Central Avenue, Shop No 6, Eastleigh Junction,EdenvaleGauteng",
  "Shop 56, N1 Value Centre, Solly Smiedt St,Goodwood Cape TownWestern Cape",
  "12 Irwin Street,MusinaLimpopo",
  "420 Jabu Ndlovu St, CBD,PietermaritzburgKwazulu-Natal",
  "UNIT NR 2 THE GABLESJohannesburgGauteng",
  "No 7 Charles De Gaulle Crescent, Highveld,CenturionGauteng",
  "34 Vonweilligh Street, Rustenburg,",
  "Illovo Thrupps Centre, 204 Oxford Road,Illovo Ext 1 SandtonGauteng",
  "Banbury Cross Village, Malibongwe & Olievenhout Ave,NorthridingGuateng",
  "VAT No. 4220120705 | 20 Olywenhout Street BosmontJohannesburgGauteng",
  "Medicross Westering, 541 Cape Rd,Linton Grange GqeberhaPort Elizabeth",
  "34 Von Wielligh Street RustenburgRustenburgNorth West",
  "Block 1, 2nd Floor, Suite 205, Mediclinic Vergelegen,Main Road Somerset WestCape Town",
  "77 Miller Street, Sophiatown,RandburgGauteng",
  "13 Hudsons Street Greenpoint,Cape TownWestern Cape",
  "Room 2, Dada Square, 52 Market St,PolokwaneLimpopo",
  "220 Voortrekker Road, Maitland,Cape TownWestern Cape",
  "72 Marais Street,BrooklynGauteng",
  "Sunset Dental, 11 Ocean Way,Sunset BeachWestern Cape",
  "Hazeldean,PretoriaGauteng",
  "Vat No: 4260174026- Suite 606, 6th Floor,Lister Medical Centre195 Jeppe Street Johannesburg",
  "Cnr Rachel De Beer and West Street,Pretoria NorthGauteng",
  "ROOM 101 CONSTANTIA DAY HOSPITALJOHANNESBURGGAUTENG",
  "85 Dorp Street, Stellenbosch,Cape TownWestern Cape",
  "The Health House, Shop 5, Cnr Rietfontien & Dayan Road,Jansenpark. BoksburgGauteng",
  "SHOP 207, WONDERPARK SHOPPING CENTREPRETORIAGAUTENG",
  "Olivedale Clinic Suite 4C Pres Fouche RoadOlivedaleGauteng",
  "Suite 120, 1st Floor, Cnr Jan Smuts & 6th RoadHyde Park JohannesburgGauteng",
  "7A North Hoeworld Centre, Cnr Malibongwe & Rocky Street,Strydom Park",
  "553 Vreyten Street, Faerie Glen X6,PretoriaGauteng",
  "SUNSET SQUARE 7 SUNSET LANEJOHANNESBURGGAUTENG",
  "2 A SCHRODER STREET UPINGTON NORTHERN CAPE 8801",
  "Thinc Clinic, Building No 3, Rivonia Office Park, 150 Rivonia Rd,SandtonGauteng",
  "SUITE 120, 1ST FLOOR CNR JAN SMUTS & 6TH ROADHYDE PARK JOHANNESBURGGAUTENG",
  "Sefako Makgatho University Campus, (Next to George Mukhari Hospital), Ga-Rankuwa,The Dental Buidling Room S153First Floor ( Tel 012-521 4889)",
  "34 Kaap de Goede Hoop Laan, Hartenbos,Mossel Bay",
  "Bedford Axis, 6 Bradford Road,BedfordviewGauteng",
  "577 Rubenstein Drive, Moreleta Park,PretoriaGauteng",
  "Postnet Suite 294 Private Bag x1672GrahamstownEastern Cape",
  "Dr Pixley Kalsaka Seme Hospital, 310 Bhejane Street, KwaMashu,Must go to Main Stores - Supply ChainAtt Siphesihle Ngiba-072 631 1407",
  "P.O.BOX 12403 Hatfield 28",
  "SHOP 25 PARKLANE CENTREPIETERMARITZBURGKZN",
  "9 Ontdekkers Road, Witpoortjie,Roodepoort",
  "5 New Road Office Park, Midrand,Johannesburg",
  "Vaal Dental Studio, 155 General Hertzog, Three Rivers,VereeningingGauteng",
  "Ground Floor, Bophelo House Block C-West, Opposite Main Door, C/O Charlotte Maxeke and Harvey Road,BloemfonteinFree State",
  "CPT Office, Equites Park,Cape FarmsWestern Cape",
  "154 KLOOF STREET ORANJEZICHT 8001 021 424 5683",
  "Shaya Pillay, 541 Cape Rd,Linton Grange GqeberhaPort Elizabeth",
  "1 Robert Broom drive, RangeviewGauteng",
  "58 Voortrekker Road, Alberton Mall,JohannesburgGauteng",
  "1st Floor Letterstedt House, Cnr Main & Campground Road,Newlands Cape TownWestern Cape",
  "Shop 3, 88 Catford Cres, Clayfield,PhoenixKwaZulu-Natal",
  "8 Bridgeway, Century City,Cape TownWestern Cape",
  "20 Olywenhout Avenue, Bosmont,JohannesburgGauteng",
  "Unit 2, Amorosa Office Park, 68 Lawrence Road,AmorosaJohannesburg",
  "49 Hill Street,KroonstadFree State",
  "Unit 22, Block C, Cedar Tree Office Park, Cnr Cedar Rd and Stinkwood Close, Opposite Fourways Life Hospital,Fourways JohannesburgGauteng",
  "Smart Smile Dental Clinic, 9 Athens street, Uitzicht, Durbanville,Cape TownWestern Cape",
  "2nd Floor, Hatfield Plaza Shopping Centre, 1122 Burnett StreetHatfieldGauteng",
  "70 6th Avenue, Newton Park, Gqeberha,Port ElizabethEastern Cape",
  "1201 Justice Mahomed Street BrooklynPretoriaGauteng",
  "34 4th avenue, Melville,JohannesburgGauteng",
  "Olivedale Hospital, Suite 202 Olivemed Building Olivedale Randburg2058",
  "11 MILLSTREAM, ECO PARK ESTATE, HIGHVELD,CENTURIONGAUTENG",
  "Corner Archer Fisher & Angel Fisher drives,MidrandGauteng",
  "The Well Medical & Dental Centre, Suite2, Kirsty CL,BallitoKwaZulu-Natal",
  "27 Saffraan Avenue, Die Boord,StellenboschWestern Cape",
  "Rosepark Dental, 53 Gustav Cres, Fichardt Park,BloemfonteinFree State",
  "583 BROADBURY CIRCLE CORNWALL HILL ESTATEIRENE X 10CENTURION",
  "Johannesburg,Gauteng",
  "No3 Industry Road, Clayville,OlifantsfonteinGauteng",
  "38 Bruce St Hillbrow, Berea,JohannesburgGauteng",
  "Suite 11, Ground Floor, Highveld Shopping Centre, Cnr Logan & John Voster Drive,CenturionGauteng",
  "206 Basden Ave, Lyttelton AH,Centurion",
  "Entrance 7 Shop U58 Cradlestone Mall, Cnr Hendrik Potgieter & Furrow Road,KrugersdorpGauteng",
  "44 Akaskia Street, Eastern Extension,George EastWestern Cape",
  "73 Musgrave Road, Musgrave, Berea,DurbanKwaZulu-Natal",
  "Shop3, Sunhill Centre,Tana RoadSunninghill Gauteng",
  "Medicross, Cnr Stone & Long street CentralKimberley",
  "82 MONUMENT ROAD NIMROD PARK KEMPTON PARK",
  "Practice No 5442095 22 William Street Newton ParkPort ElizabethEastern Cape",
  "437 Rodericks Avenue, Lynnwood,PretoriaGauteng",
  "2 Eagle Road, Cnr of Southbroom & Eagle Avenue,Hibiscus CoastKZN",
  "Sandton,Gauteng",
  "Stand 1B, Morgenson Newstand Medical Centre, Fourways Stop, Rural, 1061,Glen CowieLimpopo",
  "006 MIDLANDS OFFIC PARK EAST, MOUNTAIN QUARRY STREET, MIDSTREAM 1692",
  "64 Michelle Avenue, Randhart,AlbertonGauteng",
  "58 VOORTREKKER ROAD ALBERTON MALLJOHANNESBURGGAUTENG",
  "Windhoek,",
  "50 Loop Street,ParysFree State",
  "Polokwane,Gauteng",
  "Unit 19, 15 On Orange Hotel Corner Orange Street & Grey's Pass, Gardens,Cape TownWestern Cape",
  "06 Kirsten Street, Vandia Grove,RandburgJohannesburg",
  "V&A Waterfront, 2nd Floor,3 Dock Road, Waterway House, North Block,WaterfrontWestern Cape",
  "CNR WITKOPPEN & STONEHAVEN RD, Cnr Witkoppen & Stonehaven Road, Cambridge CrossingBryanston SandtonGauteng",
  "22 Karee Street, Block D, Suite 4,Southdowns Office ParkCenturion",
  "13 Scott St, Waverley,SandtonGauteng",
  "Block G, First Floor, Lake Umuzi Waterfront, Kiewiet street,Secunda",
  "Shop 3f Garden Centre Broadacres Shopping Centre, Cnr Cedar &, Valley Rd,Broadacres ParkJohannesburg Gauteng",
  "86B Marsh Street, Moss Bay Central,Mossel BayWestern Cape",
  "9 Balfour Road,VincentEast London",
  "162 Old Main Road, 14 Medical Towers,IsipingoKwaZulu Natal",
  "75 George Storrar DriveGroenkloofPretoria",
  "University of the Western Cape Robert Sobukwe Road Bellville 7535VAT Registration Number: 4120105111",
  "10 Medical Suite, Killarnary Mall,JohannesburgGauteng",
  "9 Ascot Court, Loxton Road,MilnertonCape Town",
  "253 Main street WaterkloofPretoriaGauteng",
  "Suite 1 Sunford Medical Center, 1 Sunford Drive , Unit 15,Phoenix DurbanKwaZulu Natal",
  "Unit 4 Building 76 Tijgervallei Office Park, 76 Pony Street, Silver Lakes,PretoriaGauteng",
  "Pretoria Gauteng",
  "C/o Zuidend & Jouberts Streets,Piet RetiefMpumalanga",
  "Cape Town, Western Cape",
  "478 Koedoesnek Ave Castle Gate Lifestyle Centre, Waterkloof Ridge,PretoriaGauteng",
  "Room 202 Cure Day Clinic, 506 Jochemus Street ErasmuskloofPretoriaGauteng",
  "53 2nd Avenue, The Houghton Medical Suites Gate 2,JohannesburgGauteng",
  "162 Enkeldoorn Avenue, Montana Park,",
  "5 Ashstead Road, Green Point,Cape TownWestern Cape",
  "6 Colenso Street, Paulshof,Gauteng",
  "Unit 4, 4 Homestead Avenue,BryanstonGauteng",
  "Shop 8, Nagiahs Mall Cnr Le Roux Avenue and Smuts Dr. Halfway House,",
  "Room 107 Nelmed Forum, Cnr Nel & Rothery Street, Nelspruit,MbombelaMpumalanga",
  "10 Plein Street, Durbanville,Cape TownWestern Cape",
  "41 Olsen Road, Bluff,DurbanKwaZulu Natal",
  "145 Second Avenue, Parkmore,SandtonGauteng",
  "353 Rivonia Boulevard Corner of 10th Avenue & Rivonia Boulevard Rivonia Sandton Edenburg,Rivonia JoahnnesburgGauteng",
  "33 Mare Street, Heidelberg,Heidelberg - GPGauteng",
  "53 St, Albans Avenue Mayfair WestJohannesburgGauteng",
  "Kabokweni RoadKabokweniMpumalanga",
  "Johannesburg, Gauteng",
  "No. 9 Shasons Centre, Cnr Warren & Shippard Street,MafikengNorth West",
  "Shop 3, Sunninghill Centre, 24 Tana Road,Sunninghill SandtonGauteng",
  "32 Andrew Whyte,SwellendamWestern Cape",
  "Cambridge Medical Suites, Cambridge Crossing Shopping Centre,Cnr Stonehaven & Witkoppen RoadsPaulshof Gauteng",
  "East Point Medical Centre, 1st Floor, East Point Mall,Cnr Rietfontein & North Road Jansen ParkBoksburg",
  "24B Tom Jones Street, Benoni South,BenoniGauteng",
  "27 Arbour Road, Heatherlands,GeorgeWestern Cape",
  "120 Mayibuye Drive, Umlazi P,Umlazi",
  "Mbombela Mpumalanga",
  "44 Akasia Street, Eastern Extension,George EastWestern Cape",
  "Beau Dental Clinic, Mozart Road Honeydew RidgeRoodepoortGauteng",
  "Lenmed Clinic Suite A4 Lenasia, 1820 VAT 4550128302",
  "227 Greenacres Hospital, Greenacres,Port ElizabethEastern Cape",
  "1 Acacia Street NorthmeadBenoniGauteng",
  "Infinity Health Medical Centre, Vat No: 4690290699, 24 Phakamile Mabija Road,Cnr Dutoitspan Road Shop 4Kimberly",
  "39 Kloof Street, Gardens,Cape TownWestern Cape",
  "5b Jatra Building, 71 Vanwijk Street,MbombelaMpumalanga",
  "Suite A, Medical & Dental Centre, 82 Corlette Drive, Melrose North,JohannesburgGauteng",
  "Cape Town,Western Cape",
  "Shop 174B, Lowveld Mall,HazyviewMpumalanga",
  "11 Louis Pasteur Arcade Schoeman Street,Pretoria CentralPretoria",
  "Room 4 Ma-Magi Office Park, 62 Marone Street,BurgersfortLimpopo",
  "23-27 Harry Trichardt street Cleary EstatePort Elizabeth",
  "Suite 112 1st Floor Pretoria North Medical Centre, 259 Burger Street,Pretoria NorthGauteng",
  "Dunkeld West Centre Suite 1107, Jan Smuts avenueDunkeld WestGauteng",
  "145 Seboane Street, Ipeleng,KimberleyNorthern Cape",
  "Sandton,JohannesburgGauteng",
  "Unit 14, 3 on Crescent, Cascades Cres, Cascades,PietermaritzburgKwaZulu-Natal",
  "EMFULENI MEDICLINIC BLOCK D 6 JAN VAN RIEBEEK BLVD VANDERBIJLPARK 1911",
  "2nd Avenue Shopping Centre, Cnr Second & Jim Fouche' Road,VerwoerdparkAlberton",
  "Room 247, Yellow Block Level 4, Inside Chalotte Maxeke Hospital,Parktown Johannesburg",
  "86A Keiskamma Street, No 9 Arorand Square,MiddelburgMpumalanga",
  "Fordsburg Clinic, 22 Bonanza Street, cnr Main Reef Road,FordsburgJohannesburg",
  "Medicross Hayfields Hayfields MallHayfieldsPietermaritzburg",
  "SHOP 8 NAGIAHS MALL CNR LE ROUX AVENUE _AND_ SMUTS DR HALFWAY HOUSE 1685",
  "53 Voortrekker Avenue, Edenvale,JoahnnesburgGauteng",
  "176 Main Street. Nieuw Muckleneuk,PretoriaGauteng",
  "5 Oxford Str,DurbanvilleCape Town",
  "305 Kildare Avenue, Bronberrik,",
  "23 Mel Mentz Street,ErmeloMpumalanga",
  "149 Cnr 3rd & President Reitz Avenue Westdene,BloemfonteinFree State",
  "Khomas Medical Centre - B1 Mall, Cnr Florence Nightingale & Alies Street,KhomasdalWindhoek",
  "0726 Lobedu Street, Daveyton,BenoniGauteng",
  "Pretoria,Guateng",
  "11 Selby Rd, Rosebank,JohannesburgGuateng",
  "870 Barnard Steet, Elardus Park,PretoriaGauteng",
  "PretoriaGauteng",
  "Lifestyle Crossing, Cnr Hendrik Potgieter & Nic Diederichs Roads,WilgeheuwelGauteng",
  "JJS Dentistry, 3 Dock Road Waterway House North Block, 2nd FloorCape TownWestern Cape",
  "Corporate Corner, 21 Via Latina Cres, Irene,CenturionGauteng",
  "Sekete Health and Wellness Centre, 203 Corner Tubela and Sontaga Road, Phooko Section,KatlehongGauteng",
  "39 Carl Cronje Drive, Shop G28, Willowbridge Shopping Centre,Bellville Cape TownWestern Cape",
  "19 Longships Drive,Plettenberg Bay",
  "PRETORIA",
  "Smith & Van Lierop Dentistry, Piazza Level, Letterstedt House, Cnr Main Road and Campground Road,Newlands Cape TownWestern Cape",
  "JohannesburgGauteng",
  "40 Marais Street HeidelbergHeidelberg - GPGauteng",
  "Suite C111 Lenmed Clinid 8 Marlin Avenue Lenasia Ext 8, LenasiaJohannesburgGauteng",
  "Hyde Park Corner Shopping Centre, Suite 122 First Floor North Wing c/o Jan Smuts & 2nd Street,Hyde ParkGauteng",
  "Block D, # 12, 7th Ave Parktown North,Parktown NorthJohannesburg",
  "Shop A, Medicare Centre, 19 Nuweland Street,Reyno RidgeWitbank",
  "Hill Park Building, 49 Hill Street Central,KroonstadFree State",
  "62 Chester Rd, Bryanston,JohannesburgGauteng",
  "Vat number: 4540285931, 118 Eland Street,Hoedspruit",
  "207 Shilling Street, Queenswood,Pretoria",
  "40 AERODROME DRIVE NORTHMEAD EXT 3 BENONI 1501",
  "9 Tarentaal Street Cnr Flamingo Street,Sedgfield6537",
  "14 Glenridge Road, GrayleighWestvilleKZN",
  "Leedent Ltd Dental Clinic & Lounge 1st floor Melrose palace building royal road curepipe next to Nevada Curepipe MU",
  "23th Ave 4th Ave Mellville Gauteng",
  "Smit & Winkel Dental Practice 2 Mountainview Drive,Bellville Cape TownWestern Cape",
  "313 DURBAN ROAD PORT ELIZABETHPORT ELIZABETH",
  "583 Broadbury Circle, Cornwall Hill Estate,Irene X 10Centurion",
  "The Well Medical & Dental Centre, Suite 2,Kirsty CL BallitoKwa-Zulu Natal",
  "15 Normandy Gardens Estate, Kirkness Avenue,Pierre van Ryneveld",
  "76 Bonanza Bay Road, Beacon Bay,East LondonEastern Cape",
  "2 Knysna Road, Loeriepark,GeorgeWestern Cape",
  "26 GARDNER WILLIAMS AVENUECAPE TOWNWESTERN CAPE",
  "94 Pretorious StreetMokopaneLimpopo",
  "Suite 205, Second Floor, Free State Medical Centre,29 Poole StreetBrandwag",
  "29 Jensen Road, The Orchards,AkasiaGauteng",
  "Shop 174B, Shop 174B,HazyviewMpumalanga",
  "Block C, Lonehill office Park,LonehillGauteng",
  "3 DOCK ROAD WATERWAY HOUSE NORTH BLOCK 2ND FLOOR",
  "Magaliesberg,Gauteng",
  "Brumelia House , 11 Kooperasie Street,VredendalWestern Cape.",
  "2416 Tshepe Close Ext 9, Gaborone",
  "2A Park Road, 502 Earlgo Buidling,GardensCape Town",
  "Ballito Drive BallitoDolphin CoastKwaZulu-Natal",
  "553 Breyten Street, Faerie Glen X6,PretoriaGauteng",
  "879 Tennis Road, Gable Office - Unit 2,Weltevreden Park",
  "40 Market Street, Bronkhorstspruit,",
  "12 Ness Avenue, Lakefield,Benoni",
  "Shop 7, Block 7A, Rodium Avenue,SteelpoortGauteng",
  "16 BOWWOOD ROAD CLAREMONT CAPE TOWN 7708 VAT NO 4380263212",
  "Medical Forum Theatre, 209 Cape Road,Newton ParkPort Elizabeth",
  "40 Wellington Street,DurbanvilleCape Town",
  "Suite 1 Savoy Medical & Dental Centre, 580 Louis Botha Ave, Gresswold,JohannesburgGauteng",
  "887 BEN SWART STREET, VILLERIA,PRETORIAGAUTENG",
  "Monumentweg 82 Monumnet Rd, Kempton Park,Gauteng",
  "265 Lenny Naidu Drive, Chatsworth,KwaZulu-Natal",
  "430 Peter Mokaba Ridge, Shop 55,DurbanKwa-Zulu Natal",
  "428 3rd Rd, Halfway Gardens,MidrandGauteng",
  "Lifestyle Garden Centre, corner Beyers Naude Drive and Ysterhout Street ,Randpark Ridge",
  "Shop 2, Shu House, Nielson Street, Korsten,Port ElizabethEastern Cape",
  "Vat no: 4720225046 - 2A Schroder Street, Upington,",
  "Pretoria,Gauteng",
  "Saldanha Property Building, Cnr Main Road & Kort Street,SaldanhaWestern Cape",
  "Shop 4 Groenkloof Plaza, 45 George Storrar Drive,GroenkloofPretoria",
  "17 Long street, Corner of Long and Main road,Knysna",
  "Suite D49, Life Fourways Hospital, Cnr Cedar Road, Cedar Ave W,FourwaysGauteng",
  "Shop 11d, Shoprite Centre Barkly RoadKimberley",
  "Plot 64516, Unit 105,FairgroundsGaborone",
  "Die HA Volschenk Gebou, R555 Main Road, [Next to Sasol Garage]SteelportLimpopo",
  "Polokwane,Limpopo",
  "34 Main Road, Mowbray,Cape TownWestern Cape",
  "41 Marloth Street, Nelspruit,MbombelaMpumalanga",
  "52 Fraser Street,HowickKwaZulu Natal",
  "Lehurutshe Shopping Centre MAll Shop 29Zeerust",
  "14 Killarney Terrace,PietermaritzburgKwaZulu-Natal",
  "118 Eland Street,HoedspruitLimpopo",
  "41 Du Toitspan Road, Kimberly.",
  "House No. 383. 383. 41 Dorstone Crescent, Cedar Creek Estate,RandburgGauteng",
  "195 Kenneth Kaunda Road Durban NorthDurban NorthKwaZulu-Natal",
  "76 Shannon Road, Noordheuwel,KrugersdorpGauteng",
  "29 Blouberg Road, Table View,Cape TownWestern Cape",
  "Shop 1A, Kimberley Street,PortlandCape Town",
  "CELTIS RIDGE SHOPPING CENTRE CNR RUIMTE & SEEDCRACKER STREETCELTISDALCENTURION",
  "Emalahleni Private Hospital, Suite 219B, 39 Mandela St,WitbankEmalahleni",
  "Izandi Serdyn, Columbia Street 2, Olive Estate, CroydonSomerset WestWestern Cape",
  "Volschenk Building, R555 Main Road, [Next to Sasol Garage]SteelportLimpopo",
  "106 President Street, Louis Trichardt,Limpopo",
  "Dr Matlala BP Dental Studio, 2688 Angelfish Street, Kaalfontein,MidrandGauteng",
  "27 Saffraan Ave, Die Boord,StellenboschWestern Cape",
  "34 4th Avenue, Melville,JohannesburgGauteng",
  "Suite 10, Raslouw Wellness Centre, CNR R55 Perdeblom Raslouw,Monavoni.0157",
  "28 Bazley Street, Port Shepstone,KZN",
  "Unit 12, 20 Bella Rosa Street,RosenparkBellville",
  "First Avenue Medpark, 23 First Avenue,EdenvaleGauteng",
  "26 Sutherland Avenue, Randfontein,",
  "1 Robert Broom Drive East, Rangeview,KrugersdorpGauteng",
  "5 Zurich St, Spartan,Kempton ParkGuateng",
  "Southdowns Shopping Centre, Cnr John Voster Drive & Karee Street,Irene",
  "273 Main Rd, Walmer,Gqeberha Port ElizabethEastern Cape",
  "Suite 120 Sandton City Mall, Cnr Rivonia Road & 5th Street,Sandton CityGauteng",
  "Camps Bay Dental Studio, 49 Victoria Road,Camps BayWestern Cape",
  "67 Rosemead AvenueKennilworthCape Town Western Cape",
  "Suite 3, 565 Peter Mokaba Road,DurbanKwa-Zulu Natal",
  "Lombardy Business Park, Unit 112,PretoriaGauteng",
  "197 Lois Avenue,NewlandsGauteng",
  "Shop no 7, Pieterhof Building,Whiteriver",
  "RUSTENBURG NORTH WESTRUSTENBURGNORTH WEST",
  "154 Kloof St, Gardens,Cape TownWestern Cape",
  "Shop 18 Riverside Bryanston, Bryanston Drive,SandtonGauteng",
  "Limpopo",
  "76 Mare Street,RoodepoortGauteng",
  "Lifestyle Crossing, Cnr Hendrick Ptgieter & Nic Diederichs Blvd,Wilgeheuwel RoodepoortGauteng",
  "142 Montpelier Road, Morningside, Windermere,DurbanKwa-Zulu Natal",
  "4 Park Lane, Park Town,Johannesburg",
  "Capital Junction, 1226 Francis Baard St,HatfieldPretoria",
  "DR S BHORAT & ASSOCIATES VAT NO: 4020217636GROUND FLOOR-MELOMED HOSPITALGATESVILLE",
  "Lord Charles Building, Block C, 337 Brooklyn Road,BrookylnPretoria",
  "Shop 5A Mutual Building, 12 Hereford Street,GroblersdalLimpopo",
  "59A COMISSIONER STREET SHOP 4 C & C CENTREBETHLEHEM",
  "Shop no 8, 100 Market Street, Polokwane Central,Polokwane",
  "7 Campbell Drive, Suite 2 Corals on Campbell,Umhlanga RocksKwaZulu-Natal",
  "Vat no- 4360268611- Bedford Axis, 6 Bradford Road,Bedfordview",
  "No 6 Pontac Street, Oude Westhof,BellvilleWestern Cape",
  "SHOP 271,THE GROVE MALL OF NAMIBIA CNR OF CHASIE & FRANKIE FREDERICKS STREETKHOMASWINDHOEK",
  "11 Havenlock Road, Willow Park Manor,",
  "862 Wekker Road Moreletta ParkPretoria",
  "11 12th Avenue, Parktown North,JohannesburgGauteng",
  "Kilner Park Day Hospital, 255 Anna Wilson St,PretoriaGauteng",
  "597 Jacqueline Drive, GarsfonteinPretoria",
  "The Thinc Clinic Rosebank, 22 Bolton Drive,Rosebank JohannesburgGauteng",
  "39 Kloof Street, Gardens.Cape TownWestern Cape",
  "69 Memorial Road, Monument Heights,Kimberley",
  "Unit 5, Bulding 3, Kloof Medical Center, 12 Lyngarth Road, Kloof,DurbanKwaZulu Natal",
  "Upper round Floor, 19 Orange Street Gardens,Cape TownWestern Cape",
  "Suite 6 Fountain Medical Centre, 8A Murray Smith Road,WinklespruitKwaZulu-Natal",
  "155 Landrost Street,VryheidKwaZulu Natal",
  "38 Uniefees StreetReitzEastern Free State",
  "Shop 39 Sammy Marks Square, Cnr Madiba & Lilian Ngoyi Street,PretoriaGauteng",
  "11 PALM STREET WHITE RIVERWHITE RIVER",
  "121 Sonja Street, Doringkloof,CenturionGauteng",
  "154 Belvedere Road , Claremont,Cape TownWestern Cape",
  "Stone Square, Welgevonden,StellenboschWestern Cape",
  "95 Boeing Road EastBedfordviewGauteng",
  "Dr K.I Ramela Inc, 107 High Street,MatatieleEastern Cape",
  "1026 Lukheli Street, Phola,Mpumalanga.",
  "Dieselvej 14 St,CopenhagenDenmark",
  "11 Main Road, Mellville,Gauteng",
  "Centurion,Gauteng",
  "Tudor Place 285, Durban Road,Bellville Cape TownWestern Cape",
  "Suite 205, Second Floor, Free State Medical Centre, 29 Poole Street,BrandwagFree State",
  "Vat no: 4420280028- Suite 6, Fountain Medical Centre,8A Murray Smith Road Winkelspruit",
  "M102a, 1st Floor Boulders Shopping Centre,Halfway HouseGauteng",
  "1 3rd Way RockfordPhoenixKwaZulu-Natal",
  "Hazeldean Square, Shop 37, Cnr Lynwood & Silverlakes Road,Silverlakes PretoriaGauteng",
  "28 Bolton Road, SandtonJohannesburgGauteng",
  "LASIKA HEALTH CENTRE 1918 ERASMUS STREETPRETORIAGAUTENG",
  "370 Ondekkers Road, Florida Park, Roodepoort,JohannesburgGauteng",
  "Shop 6 Kirkade, 56 Schoeman Street,PolokwaneLimpopo",
  "94 Civic Way, Uvongo Beach Road Uvongo BeachMargateKwaZulu-Natal",
  "30 Mimosa Street, Wilro Park,RoodepoortGauteng",
  "26 Sherwood Road, Forest Town,JohannesburgGauteng",
  "14 Helderberg Road, Stuart's Hill,Somerset WestCape Town",
  "Suite F1, Block C, 173 Rivonia, Morningside,Gauteng",
  "26 Crayfish Creek,RichardsbayKwa-Zulu Natal",
  "15 Voortrekker Street,ClanwilliamWestern Cape",
  "Suite 4, Sandton Medpark, Cnr Peter Place & Nursery Lane,BryanstonGauteng",
  "5A Bedford Manor, Cnr Kriby & Regent Street,BedfordviewGauteng",
  "NO 20 KLEINFONTEIN 368-JR PRETORIA 1001 082 578 9316",
  "32 St James Street, Somerset West,Cape TownWestern Cape",
  "159 Panorama Road, Rooihuiskraal,CenturionGauteng",
  "Stand 5888, Mothotlung Brits,North West",
  "3 High Street,UmhlangaKZN",
  "Suite 17, Promenade Centre, Cnr Samora Machel &, Henshall St,NelspruitMpumalanga",
  "Turnberry Village, Cleveland S Haasendal,",
  "10 Plein Street, Unit1, Durbanville,Cape TownWestern Cape",
  "ASPEN BUSINESS PARK BOSTON HOUSE, GROUND FLOORJOHANNESBURGGAUTENG",
  "Westwood Dental, Shop U060, Westwood Mall,16 Lincoln Terrace 3Westville",
  "Centre De La Vie, Second Floor,Beaty Street Die Heuwel x 8Emalahleni",
  "SUITE 116, MUSGRAVE PARK 18 MUSGRAVE ROADMUSGRAVEKZN",
  "Room 302, Link Building, 11 D.F. Malan Street,Cape Town City CentreCape Town",
  "University of Western Cape, Robert Sobukwe Rd,BellvilleCape Town",
  "Paaredvlei Specialist Medical Centre Unit 7, 26 Gardner William's Avenue, Paaredvlei,Somerset WestWestern Cape",
  "RUSTENBURG NORTH WEST 082 427 0103 phenyo@matebesidental.co.za",
  "Vat number: 4570259038 - Suite 306, Hyde Park Corner,Hyde Park",
  "3 Lester Ave,KloofKwaZulu Natal",
  "Suite 6 Rivonia Village Shopping Centre, Cnr 9th Avenue & Rivonia Boulevard,RivoniaGauteng",
  "Suite 7112, Victoria Wharf, Breakwater Blvd The V&A Waterfront,Cape TownWestern Cape",
  "MED099 541 Cape Rd,Linton Grange GqeberhaPort Elizabeth",
  "Suite 1 Promenade Medical Centre, A Z Berman Drive, Eastridge,Cape TownWestern Cape",
  "c/o Zuidend and Joubert Street 27 Joubert Street,Piet RetiefMpumalanga",
  "ERF96600 campground Road, Newlands,Cape TownWestern Cape",
  "CMC 6 CONCOURSE CRESCENT LONEHILL 2191 VAT NO: 4370110712",
  "Shop 13 Standard Bank Building, Cnr Lilian Ngoyi & Church StreetPretoria",
  "25510 Vincent Rd, Meadowlands West Zone 6,Meadowlands WestGauteng",
  "72 11th Street, Parkmore,JohannesburgGauteng",
  "Planet Dental Harare 52 East RoadHarareZimbabwe",
  "4 Rand Street,VredendalWestern Cape",
  "Shop L3 Cambridge Crossing Centre, 1 Stonehaven Road,PaulshofGauteng",
  "Enamel Clinic, 3rd Floor, De Waterkant Centre, 9 Somerset Road, Greenpoint,Cape Town.Western Cape",
  "545 Douglas Scholtz street Constantia ParkPretoriaGauteng",
  "56 Fairway, Beachwood,Durban NorthDurban",
  "SHOP 33 KYALAMI ON MAIN SHOPPING CENTRE FORSSMAN CI MIDRAND",
  "Cape Town South Africa",
  "MauritiusMauritius",
  "Room 302, Link Building, 11 D.F. Malan St,Cape TownWestern Cape",
  "74 Paterson Street, Newcastle CBD,",
  "Capital Prosthodontics - Dr A J Jagathpal , 134 Aramist Avenue NewlandsPretoriaGauteng",
  "918 Kaap De Goede Hoop Avenue HartenbosMosselbayWestern Cape",
  "84 CHURCHILL ROAD PLUMSTEADCAPE TOWNWESTERN CAPE",
  "8 SANDOWN ROAD BLOUBERG CAPE TOWN 7441",
  "Suite 19, Eting center, 211 Becket Street,ArcadiaPretoria",
  "17 Charlotte Maxeke Street, Bloemfontein,",
  "GROBLERSDAL, LIMPOPO",
  "51 Taunton Road, Wembley,PietermaritzburgKwaZulu-Natal",
  "Hyde Park Corner Shopping Centre, Suite 122 First Floor North Wing, c/o Jan Smuts & 2nd Street,Hyde ParkGauteng",
  "27 Titren Road Southway Mall, Shop 16c, Sea View RoadDurbanKwaZulu Natal",
  "83 Virginia Way,VirginiaFree State",
  "28 Matzikana Street,Vredendal.Western Cape",
  "Gate 2, 2 Cnr Baksteen & Axel Drive, Clayville,OlifansfoteinGauteng",
  "72 First street, Rusthof, Stand, Cape Town, Western Cape,Cape TownWestern Cape",
  "Vaal Dental Studio, 155 General Hertzog Rd, Three Rivers,VereenigingGauteng",
  "Vat no: 4570307563 - 41 Steyn van der Spuy Street, Secunda,",
  "8th Floor, Sanlam Building, Independence Avenue,Windhoek",
  "Block 1, 2nd Floor, Suite 205, Mediclinic Vergelegen, Main Road,Somerset WestCape Town",
  "242 Ontdekkers Rd, Horison,RoodepoortGauteng",
  "Polokwane",
  "VAT Number: 4450218195 | 204 Oxford Road, 1st Floor, Illovo Thrupps Centre,Illovo Ext 1 SandtonGauteng",
  "Shop 23 Tembisa Plaza Andrew Mapheto Drive,TembisaGauteng",
  "81 Scott StreetNewcastle CBDKZN",
  "78 Alcade Road, Lynwood Glen,PretoriaGauteng",
  "CPT Office, Equites Park,1E Welbeloond Rd Cape FarmsWestern Cape",
  "Pineslopes,FourwaysGauteng",
  "Suite C1, Ground Floor, Abia House,Abuja`Nigeria",
  "Auas Hill Hospital, Montreux Street,Windhoek",
  "11 Hartshorne Street, Rynfield,BenoniJohannesburg",
  "123 Nellie Road,NorwoodJohannesburg",
  "Sanhall Office Park, Suite 24 1 Kirsty Cl,Dolphin Coast BallitoKwaZulu Natal",
  "Vat No: 4620173890 | Suite 603, Life Westville Hospital, 7 Spine Road,WestvilleKwaZulu-Natal",
  "497 Walter Lanham St, Bailey`s Muckleneuk,PretoriaGauteng",
  "21 San Raphael, 64 Richard Rd,Broadacres ParkGauteng",
  "Unit 9 Bellfour Office Park, Edmar St,Tygervalley Cape TownWestern Cape",
  "35 Bendor Drive Bendor Ext 8PolokwaneLimpopo",
  "PRACTICE NUMBER:0382531 H AND P MEDICAL CC 80 BEYERS NAUDE DRIVE NORTHCLIFF, 2195",
  "Vat no: 4380263212 - 16 Bowwood Road, Claremont,Cape Town",
  "C/O DR JANSE VAN RENSBURG 155 GENERAL HERTZOG STREET THREE RIVERS VEREENINGING",
  "77 Earp Street, Ophirton,JohannesburgGauteng",
  "23 4th Avenue, Melville View,JohannesburgGauteng",
  "Shop 33 Midway Mews Shop Ctr, Harry Galaun Drive,Halfway Gardens MidrandGauteng",
  "Cornelius Street, Weltevredenpark,RoodepoortRoodepoort",
  "SUITE 215A NETCARE GREENACRES HOSPITAL RING ROAD PORT ELIZABETH -6045",
  "Radhuspladsen 16,1550 Kobenhavn V",
  "18 Alwyn Street, Bassonia,Bassonia JohanesburgGauteng",
  "Harbour Bay Medical Centre - Room 2, Cnr Main and Dido Valley Road,Simons TownWestern Cape",
  "562 ROOIGRAS STREET WATERKLOOF GLENPretoriaGauteng",
  "Suite 1A 12 Mysor RoadPietermaritzburgKZN",
  "15 Helderberg Road, Stuarts Hill,Cape TownWestern Cape",
  "33 Central Avenue, Eastleigh,EdenvaleGauteng",
  "Vat No: 4530301813 -, Shop 40, Standard Bank Centre, 291 Lilian Ngoyi Street,Pretoria",
  "1 Ashvale Close, Rydalvale,Phoenix",
  "Unit B1, 6 Liebenberg Street, Liebe Forum Unit B1,NelspruitMpumalanga",
  "16 Bowwood Road, Claremont,Cape TownWestern Cape",
  "53 Gustav Crescent,Fichardt ParkBloemfontein",
  "Shop 122, Bel Air Shopping Centre,Northriding RandburgGauteng",
  "CNR WITKOPPEN & STONEHAVEN RD, Cnr Witkoppen & Stonehaven Road, Cambridge Crossing!Bryanston SandtonGauteng",
  "Cape Gate Corner Consulting Rooms, Suite B102, 1st Floor, Cape Gate Corner C/O Okavango Rd &, Belami Ave,BrackenfellWestern Cape",
  "15 Gray Street, Knysna Central,KnysnaWestern Cape",
  "Room 7a Ground Floor Medforum Building, Cnr Heunis Street & Oliver Tambo Drive,SecundaMpumalanga",
  "17 Goede Hoop Crescent, Hurlingham Manor,SandtonGauteng",
  "Shop 101, Westfleur Town Centre, Westfleur Circle,AtlantisCape Town",
  "11 HARTSHORNE STREET RYNFIELD BENONI 011 425 1120/1",
  "VereenigingShop H11 Thabong Shop Ctr, Moshoeshoe St,Boipatong VanderbijlparkGauteng",
  "43 PL Kotze Street,WesselsbronFree State",
  "Bradford Dental Clinic, 15A Bradford Road,BedfordviewGauteng",
  "3 Somerset Crescent, Durbanville,Cape TownWestern Cape",
  "Suite 1 Sunford Medical Center, 1 Sunford Drive , Unit 15,PhoenixKwaZulu Natal",
  "518 Begemann Street, Pretoria,Gauteng",
  "Redimed, 41 Grobler St, Polokwane Central,PolokwaneLimpopo",
  "Doringkloof Mall, Cnr Lupin and Aster Ave,Doringkloof CenturionGauteng",
  "SHOP 29 NEDBANK PLAZA 175 STEVE BIKO ROAD ARCADIA 012 323 5926",
  "Steelpoort, Limpopo, 1133",
  "Vat no: 4490294719, 10 Bevis Place,Kokstad",
  "Ribumed Day Clinic 370 Clark Rd,Bulwer BereaKZN",
  "Centre for Advanced Medicine 12 Scott StreetWaverleyJohannesburg",
  "418 Chris Hani Rd, Brardene,DurbanKwaZulu Natal",
  "86 Market street,PolokwaneLimpopo",
  "St. Nicholas WaySuttonSM1 1JB",
  "11 Ocean Way, Sunset Beach,Cape TownWestern Cape",
  "154 Kloof Street, Oranjezicht,Cape TownWestern Cape",
  "317 Ontdekkers Road Cnr Ontdekkers & Conrad, Ontdekkerspark,JohannesburgGauteng",
  "39 Kloof Street, Garden's,Cape TownWestern Cape",
  "7 Campbell Drive, Suite 2 Corals on Campbell,UmhlangaKwaZulu-Natal",
  "G16 Pan African Shopping Mall, Cnr Watt & 3rd Street,Wynberg SnadtonJoahnensburg",
  "95 Blaauwberg RoadTableviewCape Town",
  "406 BRAAM PRETORIUS STREET MAGALIESKRUIN PRETORIA 150",
  "14 Helderberg Road, Stuart's Hill,Cape Town",
  "26 Petunia Road, Primrose,GermistonGauteng",
  "Block E, La Rocca, 321 Main Road,BryanstonSandton",
  "2035 Marine Dr, Shelly Beach,Port ShepstoneKZN",
  "3rd Floor, De Waterkant Centre, 9 Somerset Rd,De Waterkant Cape TownWestern Cape",
  "Eros Dental Practice General Murtala Mohammed Avenue (Old Omuramba Rd), Omuramba Medical Centre Unit 8ErosWindhoek",
  "Vat no: 4950274672 -, Shop 18, Riverside Shopping Centre, 319 Bryanston Drive, Bryanston,",
  "51 Fairbairn Street, Worcester,Western Cape",
  "9b Tyger Manor Centre, Cnr Durban Road & Bill Bezuidenhout Avenue,BellvilleCape Town Western Cape",
  "46 SOMERSET STREET GRAAFF-REINETGRAAFF-REINETEASTERN CAPE",
  "Woodburn Square Shopping Centre, 15 Woodhouse Rd,ScottsvillePietermaritzburg",
  "Room 104, First Floor Medpark 2, Netcare N1 City,Goodwood Cape TownWestern Cape",
  "4 Park Lane, Century City, Ground Floor, Century Medical Suites,Cape TownWestern Cape",
  "Teneo House, Building 3, Ground Floor, Central Park on Esplanade,Century CityCape Town",
  "40 WELLINGTON STREET DURBANVILLE 7550 021 975 7478",
  "Shop Nr 13, Fedsure Forum Building,PretoriaGauteng",
  "Shop No. 2 First Floor, Willows Crossing Shopping Centre,570 Rossouw Street Die WilgersPretoria",
  "Thembisa,Gauteng",
  "562 Rooigras Street, Waterkloof Glen.PretoriaGauteng",
  "Innovative Dental Care Center, 808 Lever Road, Noordwyk,MidrandGauteng",
  "3B SKOOL STREETPAARLCAPE TOWN",
  "Pick n Pay Hyper, Faerie Glen,AtterburyPretoria East",
  "143 Selbourne Ave Lyttelton Manor,CenturionGauteng",
  "Rochester Place, Block E, 173 Rivonia Road,MorningsideJohannesburg",
  "6 Delamore Road, Hillcrest, Suite 4B, Strangeways Business Park,HillcrestKwa-Zulu Natal",
  "7 Upper Drosty Street, Cannon Hill,Uitenhage / KariegaEastern Cape",
  "Centurion Dental Studio, 285 Wilhelmina St,Wierdapark CenturionGuateng",
  "Zone 14, 20223/4 Moshoeshoes Street, Seboken Unit 14,SebokengGauteng",
  "30 Elands Close Rd, Florentia,AlbertonGauteng",
  "95 Readman Street, Wilkoppies,KlerksdorpGauteng",
  "Cnr Witkoppen & Stonehaven Road, Cambridge Crossing!Bryanston SandtonGauteng",
  "13 Murray St,NelspruitMpumalanga",
  "14 Eaton Road,GardensCape Town",
  "533 Robert Craib Street,Constantia ParkGauteng",
  "C/O Okavango Drive & Tanner Road, Brackenfell,",
  "3 Newcentre Drive, Castlehill,Newlands WestKwaZulu-Natal",
  "38 Bowwood Road, Claremont,Cape TownWestern Cape",
  "42 Bosch Street, Groenvlei,PaarlWestern Cape",
  "RANDBURG JOHANNESBURG SOUTH AFRICA 011 462 4212",
  "70 4th AVENUE Newton Park,Port ElizabethEastern Cape",
  "STE 309, Floor 3, Medforum Building,Heunis StreetSecunda",
  "56 Chamberlain Rd,East LondonEastern Cape",
  "1121 HERTZOG STREET WAVERLEY PRETORIA 0186",
  "P.O. BOX 110185 KIMBERLEY 8306",
  "Shop 4 C.B.A25 Queen StLadysmith",
  "75 Voortrekker Street, Piketberg,Western Cape",
  "Vat No: 4760281040, - 82 Pretorius Street, Heidelberg,",
  "12 Gough Road, Wembley,PietermaritzburgKwaZulu-Natal",
  "46 Louw Wepener Street, Dan Pienaar,Bloemfontein",
  "154 KLOOF STREET ORANJEZICHT CAPE TOWN 8000",
  "College Square, 183 Nelson Mandela Dr, Brandwag,BloemfonteinGauteng",
  "181 Bekker Road, Off Allandale Road opp Waterfall Office Park,MidrandGauteng",
  "57 Durban Street, Canon Hill,Uitenhage",
  "Shop 405 Blueberry Medical Center, Blueberry Square, Blueberry & Beyers Naude Drive,HoneydewGauteng",
  "Office No.4, Willow Crossing, cnr Simon Vermooten & Rossouw,Die WilgersGauteng",
  "69 1st Road, Linbro Park,JohannesburgGuateng",
  "325 Pauline Struit, Garsfontein ,Pretoria EastGauteng",
  "10 Bevis Place,KokstadKZN",
  "11 Main Road,MelvilleJohannesburg",
  "Kromboom Dental Centre, Corner Kormboom & Burwood Road,Crawford Cape TownWestern Cape",
  "85 Dorp Street, Stellenbosch,Western Cape",
  "7 Sunset Lane, Magaliessif EXT 4,FourwaysGauteng",
  "175 Greenbury Drive, Unit 2,Phoenix",
  "Vat No: 4950274672 -, Shop 18, Riverside Shopping Centre, 319 Bryanston Drive,Bryanston",
  "113 Van Rensburg Street, Parktown Estate,Pretoria NorthGauteng",
  "41 Steyn Van Der Spuy Street,SecundaMpumalanga",
  "Shop G4-5, Casterbridge Lifestyle Centre,White River",
  "Heunis street, Medforum Building, Room 3,SecundaMpumalanga",
  "4B Sheppard Drive,Nelspruit",
  "Room 107 Nelmed Forum, Cnr Nel & Rothery Street,MbombelaMpumalanga",
  "MySmile Dental Studio, Shop G4-5, Casterbridge Lifestyle Centre,R 40 White RiverMpumalanga",
  "189 Sefako Makgatho Drive Sinoville 0182 012 548 3381 / 082 779 0335Pretoria",
  "194 TRUE NORTH ROAD MULBARTON JOHANNESBURG SOUTH 2059",
  "First Floor, Suite 2, Hyde Square Shopping Centre,Cnr Jan Smuts & North RoadDunkeld West Johannesburg",
  "3 EARL STREET NEWCASTLE KZN 2490",
  "International House, Center Boulevard 5,København SDenmark",
  "26 Bompas road, Dunkeld WestJohannesburgGuateng",
  "29 Murchison Street,New CastleKZN",
  "91 Iris Road, Norwood,JohanesburgGauteng",
  "Suite 1126 Floor 11 Durdoc Centre, 460 Anton Lembede Street,DurbanKwaZulu-Natal",
  "Ermelo",
  "Trininty Village Shop 105, Knoppiesdoring Street,Randpark RidgeJohannesburg",
  "SUITE A8 NETCARE PRETORIA EAST HOSPITALMORELETA PARKGAUTENG",
  "109 Leslie Avenue, Norscot,JohannesburgGauteng",
  "Steve Mahlangu St Siyabuswa-ASiyabuswaMpumalanga",
  "GAUTENG SOUTH AFRICA",
  "INTERCARE SILVERLAKES CNR GRAHAM AND SILVERLAKES ROAD SHOP 37 HAZELDEAN SQUARE SHOPPING CENTRE PRETORIA EAST",
  "205 Highveld Eye Hospital 4 Lana Street, C/O Lana & O.R. Tambo,WitbankMpumalanga",
  "12b Library Gardens, 61 Schoeman Street,PolokwaneLimpopo",
  "Ceal Island Medical Centre, Ceals Island Dental Studio, 67 Volstruis Avenue,Yzerfontein",
  "60 Botha Street, Vrede,Free State",
  "Sanlam Building, 8th Floor, Independence Ave,Windhoek",
  "73 Harvey Rd, Oranjesig,BloemfonteinFree State",
  "Suite 7, Starwood Mall, 3 Andromeda Street,PhoenixKwa-Zulu Natal",
  "Block G, First Floor, Lake Umuzi Waterfront, Kiewiet Street,Secunda",
  "17 Schumann St, Vanderbijlpark S. W. 5,VanderbijlparkGauteng",
  "Vat no: 4950274672 -, Shop 18, Riverside Shopping Centre, 319 Bryanston Drive` Bryanston,",
  "Shop 14 1st Floor, Rink House,Port ElizabethEastern Cape",
  "1 Sunset Lane Pine Slopes AHSandtonGauteng",
  "Lifestyle Crossing, Cnr Hendrik Potgieter & Nic Diederichs Roads,WilgeheuwelGautng",
  "39 Carl Cronje Drive, #G2,Cape TownWestern Cape",
  "H & P Medical CC, 80 Beyers Naude Drive, 80 Beyers Naude Drive,Northcliff JohannesburgGauteng",
  "Matatiele Private Dental Clinic, 107 High Street,MatatieleEastern Cape",
  "Shop 1A Suite 102, 68 Adelaide Tambo Drive Durban NorthDurban NorthKwaZulu-Natal",
  "Shop 20b Union Main Centre Philani Health Centre, 51 Josiah Gumede Road,New Germany PinetownKwaZulu Natal",
  "93 GLENWOOD STREET LYNNWOOD GLEN PRETORIA 084 986 0005",
  "UMHLANGA",
  "Shop UG 37, Umdoni Centre, 28 Crompton St,PinetownDurban",
  "5 Herschel Road, Claremont,Cape Town",
  "19 Hugenote Street,MalmesburyWestern Cape",
  "9 ASCOT COURT LOXTON ROAD MILNERTONMilnertonCape Town",
  "409 Kirkness St,SunnysidePretoria",
  "7 Green Street, Bryanston,SandtonGauteng",
  "54 ONTDEKKERS ROAD ROODEPOORTJOHANNESBURGGAUTENG",
  "152 Barvale Drive, Bakerville Gardens,NewlandsDurban",
  "C123, Emerald Bay,StrandCape Town",
  "Shop G14, Colosseum, Century Way,Century CityCape Town",
  "4 Greenwich Office Park, 63 Old Main Road,KloofDurban",
  "365 Langalibalele Street,PietermaritzburgKwa-Zulu Natal",
  "SHOP G14, THE COLOSSEUM CENTURY WAY CENTURY CITY CAPE TOWN 7441",
  "2 KNYSNA ROAD GEORGE 6529 084 337 6164",
  "Shop 33A, Paledi Mall, Cnr R71 & Hospital Road,Mankweng 0727Polokwane",
  "9b Tyger Manor Centre, Cnr Durban Road & Bill Bezuidenhout Avenue,RosenparkBellville",
  "Cosmodent, 6 Pontac Street, Oude Westhof,BellvilleWestern Cape",
  "Francios Mitterrand Road, Central Flacq,Mauritius",
  "West Street ColignyColignyNorth West",
  "40 East Road, Morningside Manor,SandtonGauteng",
  "Centurion South Africa",
  "18 High Street, Second Floor, Medical Suites,Melrose ArchGauteng",
  "Shop 2, DTI Campus, 11 Robert Sobukwe Street,SunnysidePretoria",
  "2 Palmerton Road, Lonehill Dental Excellence,LonehillGauteng",
  "15 Osborn Road, Houghton,JohannesburgGauteng",
  "8277 Nkoane Road, Thabong,WelkomFree State",
  "Suite 16, Pinetown Arcade, 23/31 Hill Street,PrinetownKwaZulu-Natal",
  "Yodent Dental Services, 17 Grace, Corner Flint, Winston Park,Marondera",
  "Vat No: 4650295985 - 570 Rossouw Street, Willows Crossing Centre,Shop 2Die Wilgers Pretoria",
  "Newton Junction Mall Shop 327, Second Floor, Cnt Mariam Makeba and Carr StreetNewtonJohannesburg",
  "Av da Base N'tchinga 395 CoopMaputoMozambique",
  "Shop 10 Shoprite Centre Complex, Lange Street,LydenburgGauteng",
  "84 Churchill Road, Plumstead,Cape TownWestern Cape",
  "Shop 3 Sunhill Centre, Tana Road, Sunninghill,SandtonGauteng",
  "Dr Dipti Gunase 33 Altantic Circle,Buffalo FlatsEast London",
  "151 Cape Road, Millpark,Port Elizabeth",
  "Suite a 1 block, C Rochester Place, 173 Rivonia Rd,MorningsideSandton",
  "23 Brander Street,Nelspruit",
  "5 Tierberg Road, Parow,Cape TownWestern Cape",
  "155 General Hertzog Road, Three Rivers,VereenigingGauteng",
  "1 Northcumberland House, C/O Northcumberland Road & Parklands Main RoadParklands Cape TownWestern Cape",
  "109 High Street, Mossel Bay Central,Mossel BayWestern Cape",
  "Unit C1 White Thorn Office Park, 606 Kudu Avenue,Allens Nek RoodepoortGauteng",
  "NO 9 HARRINGTON STREET BRITS 0250 012 2526759",
  "46 Escourt Avenue, Wierda ParkCenturionGauteng",
  "4 Andries Brink Road, Pierre van Ryneveld,Centurion",
  "Paardevlei Smile Dental, 26 Gardner Williams Avenue, Heartland De Beers Precinct,Somerset West Cape TownWestern Cape",
  "Suite 3, 72 York Street,GeorgeWestern Cape",
  "597 Jacqueline Dr, Garsfontein,PretoriaGauteng",
  "44 du Plooy Street,BethalMpumalanga",
  "Nelson Mandela Children's Hospital, 6 Jubilee Rd,Parktown JohannesburgGauteng",
  "108 Granada Square 16 Chartwell DriveUmhlangaKwaZulu-Natal",
  "Vat No: 4140256282 | Lagomane Medical Centre, 1026 Lukhele Street,Phola",
  "139 General Hertzog Road Three RiversVereenigingGauteng",
  "429 Chamberlain Road JacobsDurbanKZN",
  "Vosloorus Poly Clinic, 30 Ditshego Road,VosloorusGauteng",
  "Vat no: 4140296403 - 3226 B, Shop 4,Dudu Madisha DriveMokopane",
  "416 Ropers Street, Baileys Muckleneuk,PretoriaGauteng",
  "Shop 2, Mayville Mall,Cnr van Rensburg Road & Nienaber AvePretoria",
  "5 New Rd, Carlswald,MidrandGautng",
  "123 11th Street ParkmoreSandtonGauteng",
  "83 Virginia WayVirginiaFree State",
  "SAAPD, 6 Camdebo, Lovenstein,Western Cape",
  "Suite 7, Starwood Mall,3 Andromeda StreetPhoneix",
  "Unit 104 Rd Block First Floor, Molapo Crossing,Gaborone South East district",
  "13 Sunrise Ave, Maroelana,PretoriaGauteng",
  "3 Carnation Street, Floracliffe,JohanesburgGauteng",
  "56 Fairway, Durban North,Durban",
  "25 12 Avenue, Orange Grove,JohannesburgGauteng",
  "37 Sol Harris Crescent, North Beach Medical Centre, North Beach,DurbanKZN",
  "57-59 Durban Street, Uitenhage,Eastern Cape",
  "Bradford Axis 6 Bradford Road, 2007BedfordviewGauteng",
  "32 Central Avenue EastleighEdenvaleGauteng",
  "Gate 1, Victoria Junction, Unit 13, 57 Prestwich Street,De WaterkantCape Town.",
  "99 ROAD, NO 701 CHATSWORTHCHATSWORTHKZN",
  "Cnr Witkoppen & Stonehaven Road, Cambridge CrossingBryanston SandtonGauteng",
  "3676 Nkabinde Street, Khanyalethu X1,MhluziMiddelburg",
  "UNIT NR 2 THE GABLESJOHANNESBURGGAUTENG",
  "Brakpan",
  "Cnr Kingfisher Ave & Alexander Str, Fourways,Johannesburg",
  "Ballito Junction Mall, 1 Ballito Drive,Dolphin CoastKZN",
  "Namcon Logistics, Proton Ind Park, 1 Proton Street,Chloorkop Ext 65Gauteng",
  "65 CENTRAL STREET HOUGHTON ESTATEJOHANNESBURGGAUTENG",
  "4 Andries Brink Street, Pierre van Ryneveld,Pretoria",
  "Room 104, Hatchard Place, 30 Mandela Drive,MafikengNorth-West",
  "Suite A305 Gate House Black River Park, Fir Street,ObservatoryCape Town",
  "1 Nicol Street, Emalaleni,",
  "Sunset Dentistry Fourways , 1 Sunset Lane Pine Slopes AHSandtonGauteng",
  "Room 6-29 ORAL AN DENTAL HOSPITAL Prinshof Medical Campus, University of Pretoria, 9 Bophelo Road, Prinshof, (Dineo Mlangeni)Pretoria GTGauteng",
  "Walvis Bay, Erongo, Namibia",
  "143 Gerhard Street, Die Hoewes,CenturionGauteng",
  "20 and 22 St James Road, Southernwood,East London",
  "First Floor Office 66, Davenport Square, 89 Helen Joseph Road,GlenwoodBerea",
  "Old Mutual Building, 67 Main Street,KokstadKwaZulu Natal",
  "Mathee Dental Studio 7, 9 Niblick Way, Firgrove Rural,Cape TownWestern Cape",
  "11 Millstream, Eco Park Estate, Highveld,CenturionGauteng",
  "35A Grobler Street,PolokwaneLimpopo",
  "1st Floor, East Block, Pineslopes Shopping Centre,FourwaysGauteng",
  "3 Olienhout Avenue, Bardene,Boksburg",
  "23 Harry Trichard Crescent, Clarey Park Estate, Hillside,BethelsdorpPort Elizabeth",
  "Shop No 8 De Jong Centre Cnr of Ragel de Beer and Ben Viljoen Pretoria NorthCnr of Ragel de Beer and Ben ViljoenPretoria North",
  "No. 13 Nortsoo Street, North Dzorwulu,Accra GhanaGhana",
  "Unit 24, Sanhall Park, 1 Kirsty Close,BallitoKwa-Zulu Natal",
  "CNR RACHEL DE BEER AND WEST STR PRETORIA NORTH",
  "Moopen Dentistry, Shop 10 Vorna Valley Super Spar Shopping Complex Corner of Harry Gaulan,Albertyn StMidrand",
  "665 Mabel St, Garsfontein,PretoriaGauteng",
  "06 Penny Street, Mindalore, 1739,WitpoortjieJohannesburg",
  "Maxillo-Facial & Oral Surgery Dept Tygerberg Hospital, Francie van Zijl Drive,ParowWestern Cape",
  "Beau Plateau Road, Le Village, Labourdonnais,MapouMauritius",
  "Suite 606, 6th Floor Lister Building, 195 Cnr Jeppe & Small Street,JohannesburgGauteng",
  "Smith & Van Lierop Dentistry, Piazza Level, Letterstedt House,Cnr Main Road and Campground RoadNewlands Calremont",
  "Resa Trust Building, 81 Scott Street, PO Box 176,NewcastleKwaZulu-Natal",
  "DU02 The Market Square Shopping Centre, Beacon Way,Plettenberg BayWestern Cape",
  "18 Munnik Street, Ceres,Western Cape",
  "40 Victoria Street,George CentralWestern Cape",
  "Vat No: 4530306325, 167 Stonebridge Road,Phoenix",
  "Goodcare Medi-Centre, Shop 17 Grand Central Shopping Complex, Corner of Lower Plein and Darling Street,Cape TownWestern Cape",
  "1 Nicol StreetEmalahleniMpumalanga",
  "75b Sophia Street, Fairland,RandburgGauteng",
  "CNR RACHEL DE BEER AND WEST STR PRETORIA NORTHPretoria NorthGauteng",
  "Dr Jacobeth Whiting Welgelee Plein Shopping Centre, Cnr Piet Retief & Champagne StreetWellingtonWestern Cape",
  "A , 22 Anderson St, Nelspruit Central,MbombelaMpumalanga",
  "Vat no- 4540140334- 94 Civic Way, Uvongo,KwaZulu Natal",
  "Vat number: 4180306377 - 106 President Street,Louis Trichardt",
  "1st Floor Hosh Square Centre, Main Road,TyreSouth Lebanon",
  "Shop 12 Lambton Court Shopping Centre Corner Webber, Beacon and Doak roadsLambtonGauteng",
  "1 Chapel 111 Andries Pretorius Rd Edenvale 1609",
  "PORT ELIZABETH SOUTH AFRICA",
  "simonemorkel@gmail.com 082 938 3822",
  "Aspire Dental Clinic, Shop 1E, First Floor, Ipic Centre,Sonstraal HeightsDurbanville",
  "45-47 Cuyler StreetKariegaPort Elizabeth",
  "5th Floor Arwyp Medical Centre 22 Pine AvenueKempton ParkGauteng",
  "Unit Nr 2, The Gables, Cnr JG Strydom and Tennis Rd, Weltevredenpark, Ext 25JohannesburgGauteng",
  "Lupedrian Gebou 2, Kaap de Goede Hoop Laan 29,HartenbosCape Town",
  "1995/013591/21, 541 Cape Road - Linton Grange,Port Elizabeth",
  "Suit 101, Ground Floor, 25 True N Rd, Mulbarton,JohannesburgGauteng",
  "3 Burwood Rd, Rondebosch East,Cape Town",
  "42 Hobday Cres, Silver Lakes Golf Estate,PretoriaGauteng",
  "Shop 14a San Marco Centre, Cnr Harrismith & Francis Road,Ladysmith",
  "Paarl Family Health, 147 Main Road Vrykyk,PaarlWestern Cape",
  "9 Emerald Street, Vögelstrand,Swakopmund",
  "260 JEAN AVE CENTURION 157",
  "Suite 25 West Wing Netcare Sunninghill Hospital, Cnr Bowling & Nanyuki Road, Sunninghill,SandtonGauteng",
  "2A Park Road, 502 Earlgo Building,GardensCape Town",
  "21 Lions Pride Crescent Street, Serengeti Estate,Kempton ParkGauteng",
  "69 Hope Street,KokstadKwaZulu-Natal",
  "21 Oaktree Ave, Hazelwood,pretoriaGauteng",
  "Suite 2, Advanced Groenkloof Day Hospital. Building 2, 90 Florence Ribeiro Avenue,Walker Creek Office ParkNieuw Muckleneuk",
  "LASIKA HEALTH CENTRE , ERASMUS STREET,PRETORIAGAUTENG",
  "7 Brookside Colne WayWatford",
  "14 St James Street,Somerset WestWestern Cape",
  "56 4th Avenue, Lambton,GermistonGauteng",
  "2nd Floor, Hatfield Plaza Shopping Centre 1122 Burnett StreetHatfieldGauteng",
  "City Dental Cape Town, Unit 13, Victoria Junction, Gate1, 57 Prestwich St, De Waterkant,Cape TownGauteng",
  "(Inside the Charlotte Maxeke Hospital), Room 247, Yello Block Level 4,ParktownJohannesburg",
  "Arbuthnot Street Shop 15, Scottburgh Central,ScottburghKwaZulu Natal",
  "4 PARK LANE PARK TOWNJOHANNESBURGGAUTENG",
  "Bedford Centre Office Towers, 5th Floor,BedfordviewGauteng",
  "Suite 29, San Hall Office Park, 1 Kirsty Close,BallitoKwaZulu Natal",
  "44 1st Ave, Dunvegan,Edenvale JohannesurgGauteng",
  "Shop H11 Thabong Shop Ctr, Moshoeshoe St,Boipatong VanderbijlparkGauteng",
  "Greenhill Medical CentreRandfonteinGauteng",
  "Shop 25 Lambton Garden Shopping Centre Corner Webber, Beacon and Doak roadsLambton GermistonGauteng",
  "Enamel clinic, 9 Somerset road,3rd floor de Waterkant CentreGreen point Cape Town",
  "The Director of Finance, Private bag x20,HatfieldGauteng",
  "Ceal Island Dental Studio, 67 Volstruis Street,YzerfonteinWestern Cape",
  "808 Lever Road, Noordwyk,Midrand",
  "Hyde Square Centre, Cnr Jan Smuts and North Road,Dunkeld WestFirst Floor Suite 2 office building",
  "Shop 64, Kempton Smile,Kempton Square Shopping CentreKempton Park",
  "Unit 2B 4 Bergsig Building, 9th Avenue, Da Nova,Mossel BayWestern Cape",
  "Room G03 Medpark Building, Cnr Louwtjie Rothman & Syfret Douglas Street,N1 City Cape TownWestern Cape",
  "51 Burger Street, Polokwane Central,",
  "CAPE TOWN SOUTH AFRICA 084 919 6023 naeem786mansoor@gmail.comPort Elizabeth",
  "Shop 26 Deville Shopping Centre, 36 Main Street,Durbanville Cape TownWestern Cape",
  "Suite 1, 1st Floor, Absa Block, 2 Whyte Street,NewcastleKwa-Zulu Natal",
  "23 Austin Rd, Glen Austin,Midrand",
  "1,2 Smile Investments (Pty) Ltd, 1 Bryanston Drive, Bryanston,JohannesburgGauteng",
  "4 Andries Brink Street, Pierre van Ryneveld,PretoriaGauteng",
  "South Building 13 Scott StreetWaverley JohannesburgGauteng",
  "Multichoice Wellness Centre, 251 Oak Avenue,RandburgGauteng",
  "Arun Place, Building 6, Suite E Sir Lowry's Pass Road,Somerset WestCape Town",
  "Dentists @ Health - Summerstrand, Cnr of 8th & Blackpool,SummerstrandPort Elizabeth",
  "40 Adelaide Tambo St,VolksrustMpumalanga",
  "4 Sir Lowry Pass, Gordon's Bay,Cape TwonWestern Cape",
  "101A George Storrar Dr, Groenkloof,PretoriaGauteng",
  "5 Constantia Crescent, Stellenberg,Cape TownWestern Cape",
  "17 Long street, Corner of Long and Main road,KnysnaWestern Cape",
  "1201 Justice Mahomed, Brooklyn,PretoriaGauteng",
  "My Family Dentist&lt; Shop 31 Burgundy Square Centre Corner of Burgundy Drive and Tygervalley Road,BothasigCape Town",
  "227 Panorama Rd, The Reeds,CenturionGauteng",
  "25 12th Avenue, Orange Grove, (Opposite Netcare Linksfield Hospital),JohannesburgGauteng",
  "Wright Millners CPT Office, Equites Park, 1E Welbeloond RdCape FarmsWestern Cape",
  "1011 Pierneef Street, Villieria,PretoriaGauteng",
  "P O Box 1690, Marlboro,Johannesburg.",
  "1 Riverton Road, Scottsville,PietermaritzburgKZN",
  "Fountain Square, 15 Dolerite Street,Middelburg 1055",
  "30 B Jorissen Street, Polokwane,PolokwaneLimpopo",
  "24 Ravenswood Road, 2 Palm Resort,Parklands Cape TownWestern Cape",
  "15B Spiral Walk, Woodmead,SandtonGauteng",
  "11 Hidipo Hamutenya Street, Mediwise CentreGrootfontein",
  "7 Boxer Centre, C/o 1st & Chadwick Avenue,AlexandraGauteng",
  "VAT Number: 4370110712 | Block C, Londehill Office Park,LonehillGauteng",
  "6 Kirsten Street, Vandia Grove,SandtonGauteng",
  "39 Brown Street Suite 02, LG Nelbro BuildingNelspruit",
  "VAT Number: 4640176717 | 18 Alwyn Street, Bassonia,JohannesburgGauteng",
  "20 Olywenhout Avenue,OLYWENHOUT AVENUE Bosmont,JohannesburgGauteng",
  "East Point Medical Centre, 1st Floor, East Point Mall,Cnr Rietfontein & North RoadBoksburg",
  "Suite 3, 565 Peter Mabobo Road,DurbanKwa-Zulu Natal",
  "Shop 13, Sentrum Centre, 50 Voortrekker Street,AlbertonGauteng",
  "LEHURUTSHE SHOPPING CENTRE, MALL SHOP 29ZEERUST",
  "71 Main Street DESPATCH 6220 VAT NUMBER: 4290213869DespatchEastern Cape",
  "534 Gert Potgieter Street, Garsfontein X8,GarsfonteinGauteng",
  "177 Jan Smuts Avenue,Parktown NorthGauteng",
  "Paaredvlei Specialist Medical Centre, 26 Gardner William's Avenue, Paaredvlei,Somerset WestWestern Cape",
  "233 Route De Cilaos,La Riviere La Riviere Saint Louis",
  "40 Adderley Street,OudtshoornWestern Cape",
  "55 Bergvliet Road,BergvlietCape Town",
  "Suite 2, Victoria Medical Centre, 157 Victoria Road,Pietermaritzburg",
  "11A Loch Road, Bryanston,SandtonGauteng",
  "Smile Avenue Family Dentistry Blue Valley Shopping Centre, Shop A6 (Upper Level), Coatbridge Road, Kosmosdal,CenturionGauteng",
  "Room 101 Constantia Clinic Cnr Ontdekkers & Christaan de Wet StreetFlorida Park RoodepoortGauteng",
  "First Floor, Calyso Centre, No 2, Krugerrand Street Central,RichardsbayKzn",
  "93 Glenwood Street, Lynnwood Glen,PretoriaGauteng",
  "Ground Floor Wernhil Park, Mandume Ndemufayo Avenue,KhomasWindhoek",
  "Smalonane 2, Straume,",
  "4 Kerk Street, Fairview,EmpangeniKZN",
  "13 NEWLANDS ROAD CLAREMONTCAPE TOWNWESTERN CAPE",
  "Vat Number: 4550166427 | Suite 2 Bristol House, No 1A Shongweni Road,HillcrestPietermaritzburg",
  "78 Alcade Road, Lynwood Glen,Akasia PretoriaGauteng",
  "Shop15 Ottery Value Centre (Behind Momentum Real Estate office), Ottery,Cape TownWestern Cape",
  "Shop No. 31 Northgate Shopping Centre, Northumberland Ave,Northgate JohannesburgGauteng",
  "68A Fairbairn Street,WorcesterCape Town",
  "Namibia South Africa",
  "Shop 3, Ocean View Spar Complex, Ocean View,Swakopmund",
  "Annex 116, Mediclinic Milnerton, Cnr Racecourse & Koeberg Rd,MilnertonCape Town",
  "1st floor, Suite 106, Netcare Umhlanga Hospital, Medical Centre,321 Umhlanga Rocks DriveUmhlanga Rocks",
  "Umed Sandton Medical Suites, 134 Grayston Drive, Sandown,SandtonGauteng",
  "101 Medical Centre, 321 Burger Street,PietermaritzburgKwa-Zulu Natal",
  "101 MEDICAL CENTRE 321 BURGER STRPIETERMARITZBURGKZN",
  "VAT Number: 4760281040 | 82 Pretorius Street,HeidelbergGateng",
  "39 General Hertzog Rd,Three RiversVereeniging",
  "23 Surrey Road, Vincent 5217,East London",
  "6 Liebenberg Street, Liebe Forum Unit B1,NelspruitMpumalanga",
  "140 Uppereast Road, Mt Pleasant,Harare",
  "Vat No: 4310293370 | 553 Breyten Street, Faerie Glen X6,PretoriaGauteng",
  "24 Corner Garden Road & Mispel Avenue. The Orchards,Akasia PretoriaGauteng",
  "1st Floor, East Point Mall, East Point Medical Centre, Cnr Rietfontein and North Rand Road,Jansen ParkBoksburg",
  "70 6th Avenue, Newton Park,Port ElizabethEastern Cape",
  "Suite A19, Netcare, Pretoria East Hospital, Netcare St,Moreleta Park PretoriaGauteng",
  "Shop 505, 5th Floor, Bedford Centre , Smith Rd,BedfordviewGauteng",
  "38B 18th Street Menlo ParkPretoriaGauteng",
  "127 Ivy Rd, Norwood,SandtonGauteng",
  "10 Marble Ray Road, Newlands East,KZN",
  "33 Monument Road, Kempton Park,",
  "19 Lourensford Road, Somerset West,",
  "12 Eftyhias Park, 456 Veronica Street,MontanaPretoria",
  "Botha St,VredeFree State",
  "91 Roan Street, Mackenzie Park,BenoniGauteng",
  "15 OSBORN ROAD HOUGHTONJOHANNESBURGGAUTENG",
  "DP5 Lo Preneuse Apartments, La Preneuse Road,Carlos MorcellementTamarin Black River",
  "7B Petrusa Street, Belville,Cape TownWestern Cape",
  "313 Durban Road, Korsten,Gqeberha (Port Elizabeth)Eastern Cape",
  "2 Egret Close,Magaliessig",
  "Cnr Koedoe Street & Van Der Bijl Street ThabazimbiThabazimbiLimpopo",
  "42 Kenilworth Road, Kenilworth,Western Cape",
  "52 East Road, Avondale,HarareZimbabwe",
  "No 20, Kleinfontein 368-JR,PretoriaGauteng",
  "101 Panorama Shopping Center, Hendrik Verwoerd Drive,PanoramaCape Town",
  "SHOP 126 TYGERVALLEY CENTRE WILLIE VAN SCHOORCAPE TOWNWESTERN CAPE",
  "Shop No.6, Habitat Centre, Cnr R44 and N2,Somerset West Cape Town.Western Cape",
  "Welwitschia Medical Centre, Dr Putch Harris Drive,Walvis BayErongo",
  "38 Friedberg Street,Modimolle",
  "46 Brand Street, PPietermaritzburgKZN",
  "SUITE 7, STARWOOD MALL 3 ANDROMEDA STREET PHOENIX 4068PhoenixKwa-Zulu Natal",
  "46 Somerset Street, Graff-Reinet,Eastern Cape",
  "9 Somerset Road, De Waterkant, 3rd Floor,Green Point Cape TownWestern Cape",
  "80 Pierneef Blv, Kookrus,MeyertonGauteng",
  "45-47 Cuyler Street,Central UitenhagePort Elizabeth",
  "2 Knysna Road, Loerie Park,George EastWestern Cape",
  "72 First street, Rusthof,Stand Cape TownWestern Cape",
  "The Well Medical & Business Centre, Suite 2 Upper Level, Kirsty Close,BallitoKwaZulu-Natal",
  "Paulsof,Gauteng",
  "UWC, Robert Sobukwe Road, Bellville,Cape TownWestern Cape",
  "14 Riders Road, Knopjeslaagte,Sunvalley MidrandGauteng",
  "ORACARE DENTAL SERVICES Shop 37b Alex mall, Cnr London road and Lenin driveAlexandra SandtonGauteng",
  "Gauteng,",
  "Dr Razia Khammissa Oral & Dental Hospital, Cnr Bophelo & Dr Savage RoadGezinaGauteng",
  "154 OLIVER STREET BROOKLYNPRETORIAGAUTENG",
  "35 Protea Rd, Kanonkop,Middelburg",
  "VAT Number: 4450294840 | Allmed Clinic, 23 Mel Mentz Street,Ermelo",
  "10 Cavendish Street, Claremont,Cape TownWestern Cape",
  "Block E Rochester Place, 173 Rivonia Road,Morningside SandtonGauteng",
  "18 Alwyn Street, Bassonia,JohanesburgGauteng",
  "Shop 405 Blueberry Medical Center, Blue Berry Square, Blueberry & Beyers Naude Drive,HoneydewGauteng",
  "LOT 147 RAMSEY AVENUEPORT EDWARDKZN",
  "321 Badenhorst Street, Weirda Park,CenturionGauteng",
  "MINT DENTAL 7B MENLO PARK SHOPPING CENTREPRETORIAGAUTENG",
  "65 Kruger Street ErasmusBronkhorstspruitGauteng",
  "57 Burger Street,Polokwane",
  "Shop No: 4a, Standard Bank Square Lower, 50 Schoeman Street ,PolokwaneLimpopo",
  "Vat Number: 4570276305 | Cure Day Clinic, Room 202, 506 Jochemus Street,Erasmuskloof EXT 3 PretoriaGauteng",
  "Shop 4, 68 Victoria Road,Grassy ParkCape Town",
  "36 Monte Carlo Crescent, Kyalami Park,MidrandGauteng",
  "Proton Ind Park, 1 Proton StrChloorkop Ext 65Gauteng",
  "Mall, cnr Voortrekker &, Mcdonald St,GoodwoodCape Town",
  "78 Gemsbok Street,LenasiaGauteng",
  "16 Sir Benjamin Promenade Office Park, 20 Oxford Street,DurbanvilleWestern Cape",
  "SUITE C111 LENMED CLINICJohannesburgGauteng",
  "46 LOUW WEPENER STREET DAN PIENAARBLOEMFONTEIN",
  "149 PRESIDENT REITZ AVE, WESTDENE,BLOEMFONTEINFREE STATE",
  "13 Newlands Road, Claremont,Cape TownWestern Cape",
  "Enumerate Consulting CC, PO Box 1652,HoughtonGauteng",
  "202 Langenhoven Street, Oudtshoorn,Western Cape",
  "Forest Lane, Floreal,FlorealMauritius",
  "Birchmed Surgical Centre 8 Tiger StreetBirchleighKempton Park",
  "26 Petunia Rd, Primrose,GermistonGauteng",
  "172 Arum Road, 3 Arum Villas,Table View Cape TownWestern Cape",
  "2 Sycamore Street, Zwartkop,CenturionGauteng",
  "53A EDWARD RUBENSTEIN DRIVE SANDOWN X 24JOHANNESBURGGAUTENG",
  "FORDSBURG CLINIC 22 BONANZA STREETJOHANNESBURGGAUTENG",
  "WITBANK MPUMALANGA SOUTH AFRICA 083 769 0509",
  "104 True North Road, Mulbarton,Johannesburg SouthGauteng",
  "67 Austin St, Wilkoppies,KlerkdorpGauteng",
  "Hazeldean Square, Cnr Lynnwood & Silver Lakes Roads,Silver LakesGauteng",
  "Shop C4 Rosslyn Plaza, 111 De Waal Street,Akasia Ext 2 Pretoria NorthGauteng",
  "145 VASCO BLVD VASCO ESTATECAPE TOWNWESTERN CAPE",
  "145 Second Avenue ParkmoreSandtonGauteng",
  "Room K06 Mediclinic George, Cnr Gloucester Lane & York Street,GeorgeWestern Cape",
  "Shop 6, Silverside Centre, Die Ou Wapad Str,HartbeespoortNorth West",
  "Glenzicht Retirement Village, 33 East Street,Oaskdene Johannesburg SouthGauteng",
  "1068 Mdakalaan Street,PhomolongGauteng",
  "34 Main Road,KleinmondWestern Cape",
  "1,2 Smile, Kyalami Corner,Upper LevelShop 101B",
  "409 Kirkness Street, Clydesdale,Sunnyside PretoriaGauteng",
  "37c Carrington Street,MafikengMmabatho",
  "189 Sefako Makgatho Drive, Sinoville,PretoriaGAUTENG",
  "Docrats Corner, 65 Lilian Road,FordsburgJohannesburg",
  "NHC MEDICAL CENTER, GREYOWL S/CTRE, C/O BRAKFONTEIN _AND_ RASMUS 012 762 6400",
  "6A Laura Street, Gandhinagar,TongaatKZN",
  "Cure Day Hospitals, Medkin Room 966, 9th Floor, Louis Pasteur Building, 374 Francis Baard Street,PretoriaGauteng",
  "Dentists@Health, 273 Main Rd,Walmer GqeberhaPort Elizabeth",
  "44 Akasia Street, George East,Western Cape6529",
  "101 Columbine Avenue, Mondeor,Mondeor2901",
  "36 St James Road, Southernwood,East LondonEastern Cape",
  "The Club Surgical Centre, 2nd Floor,C/O Pinaster StreetHazelwood",
  "13 Shirley Street,Newton ParkPort Elizabeth",
  "42 Dorstone Crescent, 383 Cedar Creek Estate, Broadacres Drive,FourwaysGauteng",
  "28 Matzikana Street,Vredendal. Western Cape",
  "48A Grobler St, Polokwane Central,PolokwaneLimpopo",
  "Suite F4, Cavendish Place, 12 Cavendish St,ClaremontCape Town",
  "23 4th Avenue, Mellville,JohannesburgGauteng",
  "30 Bendordrive, Polokwane",
  "Cnr Stone & Long Str, CentralKimberley",
  "Vat No: 4550118402-55 Bergvliet Road - Bergvliet-",
  "69 Memorial Road, Monument Heights,KimberleyNorthern Cape",
  "San Ridge Medical Centre, Cnr New and Lever Roads,Midrand",
  "41 Marloth Street, NelspruitMbombelaMpumalanga",
  "Bakenry Mediese Sentrum, 1 Bakenry Street,LephalaleLimpopo",
  "103. 1ST AVENUE EDENDALE 1609 VAT NUMBER 4820266783Edenvale JohannesurgGauteng",
  "48 Long Street,KimberleyNorthern Cape",
  "East Point Mall, Cnr Rietfontein Road & North Rand Road,Jansen ParkBoksburg",
  "14 Plein Street,KlerksdorpNorth West",
  "133 Cowan Ntuli Street, Middelburg,",
  "107 Nelmed Forum, 38 Nel Street,NelspruitGauteng",
  "534 Gert Potgieter Street, Garsfontrein,PretoriaGauteng",
  "LENMED CLINIC SUITE A4 LENASIA, 1820 VAT 4550128302",
  "Unit 11, Life On Iris, 91 Iris Road,NorwoodJohannesburg",
  "131A Currie Rd, Musgrave,DurbanKwaZulu-Natal",
  "Medical Centre, 52A Main Reef Road,RandfonteinGauteng",
  "VAT Number: 4130180260 | Suite 215A, Greenacres Hospital, Ring Road,Newton ParkPort Elizabeth Eastern Cape",
  "38 Bruce Street HillbrowJohannesburgGauteng",
  "1 Bryanston Drive, Bryanston,Gauteng",
  "1121 Hertzog Street, Waverly,Pretoria",
  "Midpark Centre, Bhimy Damane St,MiddelburgMpumalanga",
  "58 Voortrekker Road New RedruthAlbertonGauteng",
  "4 6 De St, Delmas,",
  "Kaapweg 151, 151 Cape Rd,Port Elizabeth",
  "Medical Centre, Marine Drive,MargateKwaZuly-Natal",
  "35 Beethoven St, Vanderbijlpark S. W. 5,VanderbijlparkGauteng",
  "VISMED VORNA VALLEY SHOPPINGJOHANNESBURGGAUTENG",
  "8 monument Road, Kempton Park,JohannesburgGauteng",
  "No. 209 Cape Road Mill ParkPort ElizabethEastern Cape",
  "53 Okapi Street,LenasiaJHB",
  "20 Rooibok Ave, Hutten Heights,New CastleKZn",
  "Unit 3, Plot 5618, Broadhurst Industrial,Gaborone",
  "41 Marloth StreetMbombelaMpumalanga",
  "111 Kensington Drive,DurbanKwaZulu-Natal",
  "EAST LONDON",
  "VAT Number: 4500166329 | 3 Lester Avenue,KloofKwa-Zulu Natal",
  "81 SCOTT STREETNEWCASTLE CBDKZN",
  "De Necker Dentisty, Melville View, 23 4th Avenue,JohannesburgGauteng",
  "Gate 1, Victoria Junction, Unit 13, 57 Prestwich Street,De WaterkantWestern Cape",
  "147 Main Road VrykykPaarlWestern Cape",
  "P.O.BOX 2453 POTCHEFSTROOM 2520",
  "Shop No. 7, Foro Spar, 3602 Monareng St,lhabane Unit 1 TlhabaneRustenburg",
  "1547 Maluka Street LynnvilleEmalahleni",
  "1501 Yellowlegs Street, Zambezi Country Estate,",
  "Shop G28, Willowbridge Maill, 39 Carl Cronje Dr,BellvilleCape Town",
  "P.O. Box 20547 Gaborone,",
  "32 Harrington Street, Schoemansville,HartbeespoortNorth West",
  "Enaex Africa (Pty) Ltd, Attention Derik Strydom ( 0824690770)Nitrogen RoadSasol Complex",
  "12 Opperman Street Witbank,EmalahleniMpumalanga",
  "PO Box 2142, Walvis Bay,",
  "The Dental Studio, 39 Bendor Dr,Bendo Ext 8Polokwane",
  "Dr Andries Jonathan Taljaard -Vat No: 4090128267 - 151 Cape RoadMill ParkPort Elizabeth",
  "56 Schoeman Street Polokwane CentralPolokwaneLimpopo",
  "Suite 215A, Netcare Greenacres Hospital, Ring Road,Port ElizabethEastern CApe",
  "119 Krogh Street,Louis TrichardtLimpopo",
  "Cnr Gardens and 24 Mispel Avenue, The Orchards,Acacia",
  "Vat No - 4410286035- Shop H11 Thabong Shopping Centre, Moshoeshoe Street,SebokengGauteng",
  "Room G03 Medpark Building, Cnr Louwtjie Rothman & syfret Douglas Street,N1 City Cape TownWestern Cape",
  "Medicare Lifestyle, Maerua MallKhomasWindhoek",
  "Central Park Medical Centre, 4 Park Lane,Century CityCape Town",
  "Shop 7B, Cnr of Florin and Krugerarand Road, Strubensvalley,RoodepoortGauteng",
  "Shop No 522 Entrance 5 , Wonderpark Shopping Centre, Cnr Brits Str & Heinrich Avenue,Karenpark Akasia Pretoria North Gauteng",
  "Kaap De Goede Hoop Avenue HartenbosMossel BayWestern Cape",
  "607 KINGS WAY ROAD MEDICAL CENTRE, 2ND FLOOR AMANZIMTOTI",
  "Vat No 4240305690 - Sunset Square Medical Centre, 7 Sunset Lane, Magaliessig Ext 4,Fourways",
  "Suite 6, Dental Medical Chambers, 37 A Grobler Street,Polokwane",
  "Teneo House, Building 3 Ground Floor Central Park on Esplanade,Century CityCape Town",
  "29 Aitken Street, Cnr, De Winnaar street,Halfway HouseMidrand",
  "29 Poole St, Brandwag,BloemfonteinFree State",
  "SUITE 16, PINETOWN ARCADE 23/31 HILL STREET, PINETOWNDURBAN 3610KZN",
  "14 Glenridge Road, GrayleighWestvo;;eKZN",
  "Unit 4 Terra Nova Building, 131 Andrews Street,BloemfontienGuateng",
  "Plot 9801, Extensions 28, Partial Letlhalerwa Road,Gaborone",
  "OLD MAIN ROAD 2 MELLER ROAD",
  "31 Silverwood Estate, 51 Nicol Street,Monavani CenturionGauteng",
  "2 Limpopo St, Three Rivers,VereenigingGauteng",
  "Unit 1, 239 Norda street, Engen Garage,LeandraMpumalanga",
  "Maxofacial Clinic, 3rd Floor, C Block, Frere Hospital, Amalinda Main RoadEast LondonEastern Cape",
  "Shop 19, Union Main Centre,51 Josiaah Gumede RoadPineTown",
  "262 West Street,Pretoria NorthGauteng",
  "Vat No 4240305690 - Sunset Square Medical Centre, 7 Sunset Lane,Magaliessig Ext 4Fourways",
  "52 Morone Street, @Dr Benny Choeu Medical CentreBurgersfortLimpopo",
  "Registration number 2019/242399/07 - 5A Mills Street, Valmary Park,Durbanville",
  "230 Sidney Ave, Waterkloof,PretoriaGauteng",
  "CAMPS BAY DENTAL STUDIO, 49 VICTORIA ROAD,CAMPS BAYWESTERN CAPE",
  "127 Broadway CircleWestgateCape Town",
  "N.H.C. BRYANSTON 2988 WILLIAM NICOL DRIVE _AND_ BRYANSTON DRIVE BRYANSTON",
  "Macadamia Clinic, 56 Impala Street,White River",
  "154 Belvedere RoadClaremontCape Town",
  "273 Main Road, Walmer,Port ElizabethEastern Cape",
  "NHC Medical Center, Greyowl S/CTRE, C/o Brakfontien & Rasmus,CenturionJohannesburg",
  "Lifestyle Garden Centre, Beyers Naude Drive, Randpark Ridge,RandburgJohannesburg",
  "25 True N Rd, Mulbarton,JohannesburgGauteng",
  "257 Jan Smuts Avenue, Dunkeld West,RandburgGauteng",
  "1 RIVERTON ROAD SCOTTSVILLEPIETERMARITZBURGKZN",
  "Greenstone Park,JohannesburgGauteng",
  "88 Willem Botha Drive, Eldoraigne,CentrurionGauteng",
  "16 Goddefroy SteetSecunda",
  "DELIVERED ON YOUR BEHALF TO: DR DANETTE ROSSOUW INCORPORATEDCAMBRIDGE CROSSING SHOPPING CENTRESHOP L 13 - SANDTON 2191",
  "12 Wilderness Road,ClaremontCape Town",
  "CARLSWALD DECOR CENTRE CNR OF 5TH ANDJOHANNESBURGGAUTENG",
  "101 George Storrar Dr, Groenkloof,PretoriaGauteng",
  "WANDERERS CRICKET STADIUM",
  "Suite 3, 72 York Street,George",
  "Shop 4, Groenkloof Plaza, Cnr Baines & George,PretoriaGauteng",
  "40 4th Avenue, Newton Park,GqeberhaPort Elizabeth",
  "6 Glen Garry Rd, Pinelands,Cape TownWestern Cape",
  "SHOP 18 MEARUE LIFESTYLE CENTRE Centaurus Street,Windhoek",
  "38B 18TH STREET MENLO PARKPRETORIAGAUTENG",
  "263 RIFLE RANGE ROAD MONDEORJOHANNESBURGGAUTENG",
  "22 Huguenot Avenue, Bordeaux South,RandburgGauteng",
  "550 VAN POMMEREN STREET ELARDUS PARKPRETORIAGAUTENG",
  "73 Musgrave Rd, Musgrave,BereaKwazulu Natal",
  "Dr Yonela Zintle Putuma-Gqalangile, Cnr of AZ Berman Road & R300, Office Block K1 & K2,Watergate MallCape Town",
  "941 Henley Street Faerie GlenPretoriaGauteng",
  "Shop No 8 De Jong Centre Cnr of Ragel de Beer and Ben Viljoen Pretoria North",
  "Suite 3, Medical @ Campus, Campus Square Shopping Mall, Cnr Kingsway & University Road, Auckland Park, Johannesburg, 2092 South AfricaAuckland Park JohannesburgGauteng",
  "143 GERHARD STR DIE HOEWESPRETORIAGAUTENG",
  "Dr Meyer Oosthuizen Incorporated, Vat no 4420280028, Suite 6, Fountain Medical Centre,8A Murray Smith RoadWinkelspruit",
  "19 Longships Drive,Plettenbergbay",
  "1 Bosberg Street, Vaalpark,SasolburgFree State",
  "Emfuleni Mediclinic, Block D, 6 Jan Van Riebeeck Blvd,Vanderbijlpark C. E. 1 VanderbijlparkGauteng",
  "110 Mooirivier Drive Norkem ParkKempton ParkGauteng",
  "2nd Floor, V&A Waterfront, 3 Dock Road, Waterway House, North Block,WaterfrontWestern Cape",
  "13DE LAAN NR 7 THABAZIMBITHABAZIMBINORTHWEST",
  "628 Mohlatse Street SoshanguveGauteng",
  "1865 WILDCHESTNUT STREET PROTEA GLEN SOWETO JOHANNESBURG1818",
  "20A Kloof Road, Sarlan park, C/O Parade,BedfordviewGauteng",
  "Dr Joanne Lan (Pty) Ltd Suite 1107, 1st Floor, Dunkeld West Centre.Cnr Jan Smuts Avenue & Bompass RoadJohannesburg",
  "405 Lucky Bean Crescent, Mareletta Park,PretoriaGautng",
  "OFFICE NO. 4 WILLOWS CROSSING CNR SIMON VERMOOTEN AND ROSSOUW DIE WILGERS PRETORIA",
  "Suite 5 & 6, Mayfair on the Lake, 5 Park Ln,Umhlanga RidgeUmhlanga KZN",
  "Wilkoppies Shop 24 Macrovest Centre, Cnr Austin & William St,Wilkoppies Klerksdorp",
  "21 Hoop Street, Caledon,Cape Town.Western Cape",
  "107 NETCARE LAKEVIEW HOSPITALJOHANNESBURGGAUTENG",
  "726209910",
  "Unit 5, 10 Pepper St,Cape Town City CentreCape Town",
  "Unit 2, The Gables Office Park, 879 Tennis Road,Weltevreden Park",
  "5 Park Lane, Umhlanga Ridge,UmhlangaKZN",
  "ROOM 104 HATCHARD PLACE 30 NELSON MANDELA DRIVE MAFIKENGMafikengNorth-West",
  "All Saints Shopping Centre Cnr President Fouche and Windsor WayNorthridingRandburg",
  "Vat no 4780287365 1st Floor North Coast Medical & Dental Centre,27 Ireland StreetVerulam",
  "489 Langalibalele St,Pietermaritzburg",
  "111 Flamingo Street Avenue,Lenasia",
  "VAT No: 4100284639 | Healthcare @ 227 Panorama Rd, The Reeds,CenturionGauteng",
  "cambridge Medical Suites, Cambridge Crossing Shopping Centre, Cnr Witkoppen &, Stone Haven Rd,Paulshof SandtonGauteng",
  "325 Pauline Srtuijt, Garsfontein ,Pretoria EastGauteng",
  "2 Palmerton Road,Lonehill SandtonGauteng",
  "14 Garden Street, Grangetown,Verulam",
  "38 Belvedere Dr, Watsonia,TongaatKwaZulu-Natal",
  "31 De Grendel Road, Parow North,",
  "Shop U81, Cornubia Shopping Mall, Corner of Flanders Drive & Tacoma Drive Flanders Drive Mount Edgecombe,UmhlangaKwaZulu-Natal",
  "99 Road, No 701 ChatsworthChatsworthKZN",
  "57 Durban Street, Cannon Hill,Uitenhage",
  "Mayo Clinic, William Nicol Dr,Constantia KloofRoodepoort",
  "33 N.J. Van Der Merwe Crescent,Sasolburg",
  "@ Health Medical Centre, 260 Jean Avenue, Die Hoewes,CenturionGauteng",
  "Suite 17 Smokey Mountain Office Park, Corridor Street,WitbankEmalahleni",
  "Dis-Chem Building 289 Cape RoadNewton ParkPort Elizabeth",
  "Vat no: 4310278066, Shop 3F Broadacres Shopping Centre, Cnr Cedar & Valley Road,Broadacres",
  "Harbour Bay Mall Medical Centre,SimonstownCape Town",
  "406 Braam Pretorius Street, Pretoria,MagalieskruinGauteng",
  "P o Box 389, Cape Gate,",
  "1540 Letsatsi Str Protean NorthSowetoGauteng",
  "Welwitschia MediPark, Hidipo Hamutenya Street, Walvis Bay,",
  "Suite A8 Netcare Preoria East Hospital, Corner Netcare & Garsfontein RoadMoreltta ParkGauteng",
  "20 Doornlaagte Crescent, Lephalale",
  "577 Rubenstein Drive, Moreletapark,PretoriaGauteng",
  "20 DOORNLAAGTE CRESCENT LEPHALALE",
  "DentA Med, 17 Schumann St, Vanderbijlpark S. W. 5,VanderbijlparkGauteng",
  "76 Bonanza Bay Road, Beacon Bay,East London",
  "127 Ivy Road, Norwood,JohannesburgGauteng",
  "2 A Schroder Street, Upington,Northern Cape",
  "Dr Abraham Petrus Thomas, 4 Rand Street,Vredendal",
  "Block K1 & K2 Watergate Mall, Cnr R300 & A Z Berman Drive,Lentegeur Cape TownWestern Cape",
  "94 Peter Mokaba Street,PotchefstroomNorth West",
  "75 George Storrar Drive, Groenkloof,PretoriaGauteng",
  "11 President Square,Zeerust",
  "78 Eeufees Street, Middelburg,",
  "7 Carlton Cl, Sunnydale,Fish HoekCape Town",
  "Shop 13 Parklands Centre, Link Road,Parklands Cape TownWestern Cape",
  "75 Vortrekker Street,PiketbergWestern Cape",
  "No 8 Milner Road, North End,East London",
  "16 Pinetown Arcade, 29-31 Hill Street,Pinetown",
  "Beaulieu Office Park, Block 6, R55 Road,MidrandGauteng",
  "31 De Grendel Road, Parow NorthCape TownWestern Cape",
  "2998 William Nicol Drive, NHC Bryanston,BryanstonGauteng",
  "LENMED CLINIC SUITE A4JOHANNESBURGGAUTENG",
  "CHEMSFORD MEDICAL CENTRE BLOCK 1 107 JB MARKS RD ST AUGUSTINE'S HOSPITALDURBANKZN",
  "DURBAN KZNDURBANKZN",
  "DENTISTS@HEALTH 273 MAIN ROADPORT ELIZABETH",
  "145 RIGEL AVENUE NORTH WATERKLOOF RIDGEPRETORIAGAUTENG",
  "ROOM 22 MEDICAL CENTRE 53 BURGER STREETPOLOKWANELIMPOPO",
  "SUITE 3, 565 PETER MABOBA ROAD DURBAN 4001 dr.mookadam@gmail.com",
  "155 GENL HERTZOG STREET THREE RIVERSVEREENIGING",
  "DELIVERED ON YOUR BEHALF TO: DENTO CARE PRACTICE - 3 INDUSTRY ROADOLIFANTSFONTEINGAUTENG",
  "P O BOX 27594 GREENACRES6057",
  "51 FAIRBAIRN STREET WORCESTERWORCESTERWESTERN CAPE",
  "23 4TH AVENUE MELLVILLEJOHANNESBURGGAUTENG",
  "70 6TH AVENUE NEWTON PARKPORT ELIZABETHEASTERN CAPE",
  "5/81 DUNSWART AVENUE DUNSWART BOKSBURG 1459",
  "SUITE 120, IST FLOOR HYDEPARK CORNERJOHANNESBURGGAUTENG",
  "179 KOEDOE STREET WIERDA MALLWIERDA PARKCENTURION",
  "CNR WITKOPPEN AND STONEHAVEN RD, CAMBRIDGEJOHANNESBURGGAUTENG",
  "MISSING",
  "DELIVERED ON YOUR BEHALF TO:DR SUZANNE VAN DER LINDEN - SUITE 117FIRST FLOOR HYDE PARK CORNER -HYDE PARK -2196",
  "430 PETER MOKABA RIDGE SHOP 55DURBANKZN",
  "SHOP 4, GROENKLOOF PLAZA C/O BAINES AND GEORGE STORRAR GROENKLOOF, PRETORIA",
  "39 CARL CRONJE AVENUE SHOP G28 WILLOWBRIDGE SHOPPINGCAPE TOWNWESTERN CAPE",
  "PAARDEVLEI SPECIALITS MEDICAL CENTRECAPE TOWNWESTERN CAPE",
  "4 RAND STREET VREDENDALVREDENDALWESTERN CAPE",
  "PLOT 64516, UNIT 105,FAIRGROUNDS GABARONEBOTSWANA",
  "11 OCEAN WAY SUNSET BEACH 7441 CAPE TOWN",
  "20A KLOOF ROAD SARLAN PARK CNR THE PARADEJOHANNESBURGGAUTENG",
  "HEALTHCUBES MEDICAL CENTER RANDBURG SQUARE MALL FERNDALE, RANDBURG JOHNNESBURG",
  "SHOP 14 1ST FLOOR RINK HOUSEPORT ELIZABETHEASTERN CAPE",
  "31 CORNWELL STREETOAKDALEBELLVILLE",
  "FICHMED GA16 GUSTAV CRESCENT FICHARDT PARK 9301",
  "406 BRAAM PRETORIUS STREET MAGALIESKRUIN PRETORIA 0150",
  "OFFICE NO. 4 WILLOWS CROSSING CNR SIMON VERMOOTEN _AND_ ROSSOUWPRETORIAGAUTENG",
  "ROOM 104 HATCHARD PLACE 30 NELSON MANDELA DRIVE MAFIKENG",
  "SHOP 2 DTI CAMPUS 11 ROBERT SOBUKWE STREETPRETORIAGAUTENG",
  "5 ASHSTEAD ROAD GREEN POINTCAPE TOWNWESTERN CAPE",
  "VAT NO 4900285398PIET RETIEF",
  "10 MEDICAL SUITE KILLARNEY MALLJOHANNESBURGGAUTENG",
  "MEDICAL CENTRE 52A MAIN REEF ROAD RANDFONTEIN 1759",
  "52 MARONE STREET BURGERSFORT LIMPOPO 1150",
  "23 MEL MENTZ STREET ERMELOERMELOMPUMALANGA",
  "109 HIGH STREET MOSSEL BAY CENTRAL MOSSEL BAY 6500",
  "SUITE 6 MERCANTILE CENTER DURBAN ROADKORSTEN PORT ELIZABETH",
  "DELIVERED ON YOUR BEHALF TO: DR TEETH (PTY) LTD185 RUIMTE ROADRASLOUW CORNER PRETORIA",
  "189 SEFAKO MAKGATHO DRIVE SINOVILLEPRETORIAGAUTENG",
  "BEDFORD DENTAL CLINIC 15A BRADFORD ROADBEDFORDVIEW JOHANNESBURGGAUTENG",
  "DELIVERED ON YOUR BEHALF TO: NORTH COAST DENTAL STUDIO (PTY) LTD38 BELVEDERE DRIVE -WATSONIATONGAAT",
  "SUITE 6 FOUNTAIN MEDICAL CENTRE8A MURRAY SMITH ROAD - WINKELSPRUITKWA ZULU NATAL",
  "7-13 PETER PLACE LYME PARKSANDTON",
  "HILL PARK BUILDING 49 HILL STREETKROONSTAD0",
  "15 ON ORANGE HOTEL UNIT 9 CORNER OF ORANGE STREET AND GREYS PASS CAPE TOWN CBD",
  "135 DAISY STREET SANDTON",
  "420 JABU NDLOVU STREET PIETERMARITZBURG",
  "29 BLAAUWBERG ROAD TABLE VIEWCAPE TOWNWESTERN CAPE",
  "CITY DENTAL BUILDING 150 NELSON MANDELA DRIVEWESTDENEBLOEMFONTEIN",
  "DP0065854 131a CURRIE ROAD MUSGRAVE - 4001 051 451 1106",
  "DELIVERED ON YOUR BEHALF TO:DR MANDLA QOBOSHIYANE16 PINETOWN ARCADE- 29-31 HILL STREET-PINETOWN",
  "159 Panorama Road RooihuiskraalCenturionGauteng",
  "NETCARE ST AUGUSTINE'S HOSPITAL 107 J.B, MARKS ROADBULWER BEREAKZN",
  "DELIVERED ON YOUR BEHALF TO: DR CAREL PASSANO VAT NO: 444022653059 14TH AVENUE NORTHCLIFF",
  "UNIT 32 SANHALL OFFICE PARKDOLPHIN COASTBALITO",
  "THE WELL CENTRE SUITE NO 2 1ST FLOORBALLITOKZN",
  "UNIT C- 1 WHITETHRON OFFICE PARK606 KUDUA AVENUEALLANS NEK - ROODEPOORT",
  "DELIVERED ON YOUR BEHALF TO:DR K PATHERG14 COLOSSEUM - CENTURY CITY",
  "SUITE 17, PROMENADE CENTRE LOUIS TRICHARDT STREETNELSPRUITMPUMALANGA",
  "178 STARLING ROAD LENASIA SOUTHJOHANNESBURGGAUTENG",
  "155 GENERAL HERTZOG THREE RIVERSTHREE RIVERSVEREENINGING",
  "39 KLOOF STREET GARDENSCAPE TOWNWESTERN CAPE",
  "CLICKS CENTRE NELSON MANDELA STREETRUSTENBURGNORTH WEST",
  "Room B23, Life Fourways Hospital Cedar Avenue West, Cedar RoadFourways JohannesburgGautengq",
  "70 4th Avenue Newton ParkPort Elizabeth",
  "54 MEMORIAL WAY KIMBERLYKIMBERLYNORTHERN CAPE",
  "SHOP 174B LOWVELD MALLHAZYVIEWMPUMULANGA",
  "DR KAVENDAREN PATHER COLOSSEUM DENTAL STUDIOG14 - COLOSSEUM- CENTURY WAYCENTURY CITY",
  "Ground Floor Melomed Hospital,Gatesville Cape TwonWestern Cape",
  "MORGAN & AGATHA STREET PUSELA MEDICAL CENTRETZANEEN",
  "DORPSTRAAT 85 STELLENBOSCHCAPE TOWNWESTERN CAPE",
  "23 HARRY TRICHARD CRESCENT CLAREY PARK ESTATEPORT ELIZABETH",
  "DELIVERED ON YOUR BEHALF TO:DR SIPHEPHELO SILULEKO SIBEKOUNIT 1 23 MARKET STREET",
  "SHOP 7 BLOCK 7A RODIUM AVENUE STEELPOORT 1133",
  "70 4th AVENUE NEWTON PARK PORT ELIZABETH",
  "DELIVERED ON YOUR BEHALF TO: CDE SANDTON (PTY) LTD - SHOP 18RIVERSIDE SHOPPING CENTRE319 BRYANSTON DRIVE- BRYANSTON -2021",
  "103. 1ST AVENUE EDENDALE 1609Edenvale JohannesurgGauteng",
  "205 HIGHVELD EYE HOSPITAL 4 LANA STREETWITBANKMPUMULANGA",
  "DELIVERED ON YOUR BEHALF TODR ANDRE BRAND13 HUDSON STREET",
  "9 ASCOT COURT LOXTON ROAD MILNERTON",
  "234 ATHOL STREET HIGHLANDS NORTH 2131 011 440 0819 / 082 973 5976",
  "ROOM 4 MA-MAGI OFFICE PARK 62 MARONE STREETBURGERSFORT",
  "13 HUDSON STREET GREENPOINTCAPE TOWN",
  "1 NORTHCUMBERLAND HOUSE C/O NORTHCUMBERLAND CLOSE _AND_CAPE TOWNWESTERN CAPE",
  "POSTNET SUITE 112 PRIVATE BAG X37 LYNNWOOD RIDGE 40",
  "72 11TH STREET PARKMOREJOHANNESBURGGAUTENG",
  "BEDFORD CENTRE OFFICE TOWERS, 5TH FLOORJOHANNESBURGGAUTENG",
  "53 VOORTREKKER ROAD EDENVALEJOHANNESBURGGAUTENG",
  "SHOP NO 8 BLU VALLEY MALL, CNR ROOIHUISKRAAL & BOTHRILL AVENUETHE REEDS -CENTURION",
  "93 PRETORIA ROADBENONI",
  "INTERCARE LYNWOODSHOP 37 HAZELDEAN SQUARE SHOPPING CENTREPRETORIA EAST",
  "CNR GREAT NORTH _AND_ KEI ROAD FARRAMEREBENONIGAUTENG",
  "488 SKUKUZA STREET FAERIE GLENPRETORIAGAUTENG",
  "DELIVERED ON YOUR BEHALF TO: DR MS BABOO14 RINK HOUSE 24 RINK STREET - CENTRAL",
  "30 Bender Driver SterparkPolokwanePolokwane",
  "1 ASHANTI 52 COMPENSATIE STREETPOLOKWANELIMPOPO",
  "ASHTON HOUSE 51 LEBOMBO ROAD ASHLEA GARDENS 0081",
  "81 SCOTT STREET NEWCASTLENEWCASTLEKZN",
  "DELIVERED ON YOUR BEHALF TO: JK THE DENTIST (PTY) LTD11 12TH AVENUE PARKTOWN NORTH JOHANNESBURG",
  "101A GEORGE STORRAR ROAD GROENKLOOFPRETORIAGAUTENG",
  "DP 5 LA PRENEUSE APARTMENTS LA PRENEUSE ROADBLACK RIVERMAURITIUS",
  "CNR JAMES MAROKA & PETER MOKABA AVEPOTCHEFSTROOMNORTH WEST",
  "SHOP LO2 CAMBRIDGE CROSSINGCNR WITKOPPEN & STONEHAVEN ROADSPAULSHOF",
  "DR FELIS PINHEIRO SUITE 11, GROUND FLOOR, HIGHVELD SHOPPING CENTREHIGHVELDGauteng",
  "76 BONZA BAY ROAD. BEACON BAY,EAST LONDONEASTERN CAPE",
  "ASHTON HOUSE 51 LEBOMBO ROAD ASHLEA GARDENS 0081Ashlea GardensPretoria",
  "205 Highveld Eye Hospital 4 Lana Street, C/O Lana & O.R. TamboWitbankMpumalanga",
  "DELIVERED ON YOUR BEHALF TO: DR GUSTAV ANDRIES ERLANK30 BENDOR DRIVE - STERPARK-POLOKWANE -0699VAT NO: 4050290032",
  "67 ROSEMEAD AVENUE KENILWORTH 7800",
  "64 CHESTER STREET BRYANSTONJOHANNESBURGGAUTENG",
  "DELIVERED ON YOUR BEHALF TO: MASHAMAITE DENTAL PRACTICE ( PTY) LTD628 MOHLATSI STREETSHOSHANGUVE BLOCK XX",
  "15 GRAY STREET KNYSNA 6571 044 382 1535",
  "559 Lansdowne Road Nerissa EstCape Town",
  "7b PETRUSA STREET BELLVILLE 7530 021 946 1112",
  "64 MICHELLE AVENUE RANDHART",
  "RACECOURSE & KOEBERG ROAD MILLNERTONCAPE TOWN - WESTERN CAPE",
  "UNIT 75 JAKES GERWEL DRIVECAPE TOWNWESTERN CAPE",
  "228 Utrecht Street Unit 7VryheidKZN",
  "38 FRIEDBERG STREET MODIMOLLE",
  "14 ST JAMES STREET SOMERSET WEST 7130",
  "LIFESTYLE CROSSING CNR HENDRIK POTGIETER & NIC DIEDERICHS BLVDWILGEHEUWELGAUTENG",
  "39 KLOOF STREET GARDENSGreen Point Cape TownWestern Cape",
  "152 Barvale Drive Bakerville GardensNewlandsDurban",
  "BRADFORD DENTAL CLINIC 15A BRADFORD ROADBEDFORDVIEW JOHANNESBURGGAUTENG",
  "Broadacres Garden Centre Cedar RoadBraodacresRandburg",
  "UNIT C - 1 WHITETHORN OFFICE PARK606 KUDU AVENUEALLANS NEK - ROODEPOORT",
  "10 PRINSMAN PLACE SCHOEMAN STREETPRETORIAGAUTENG",
  "76 BONZA BAY ROAD BEACON BAY 5241",
  "26 Sherwood Road Forest TownJohannesburgGauteng",
  "Room 204 Mulbarton Medical Centre 5 True North RoadMulbartonJohannesburg",
  "DELIVERED ON YOUR BEHALF TO: MASHAMAITE DENTAL PRACTICE (PTY) LTD628 MOHLATSI STREETSOSHANGUVE BLOCK XX",
  "83 VIRGINIA WAYVIRGINIAFREE STATE",
  "81 HEATHCOCK AVENUE EXTENSION 1 - LENASIAGAUTENG",
  "Webber Rd & Oliver Street EsteraGemistonGauteng",
  "DELIVERED ON YOUR BEHALF TO: DR SIVALUXMI MUDLY - VAT NO: 4830254258NORTHRIDING MEDICAL CENTRE -SHOP 25 NORTHRIDING SQUARECNR BELLAIRS & BLANDFORD ROAD",
  "SUITE 7, STARWOOD MALL 3 ANDROMEDA STREET PHOENIX 4068",
  "437 RODERICKS AVENUE LYNNWOODPRETORIAGAUTENG",
  "81 SCOTT STREET NEWCASTLENEWCASTLE CBDKZN",
  "Route 21 Corporate Park 25 Sovereign DriveMilestone Place Block A2Irene",
  "85 DORP STREET STELLENBOSCH,CAPE TOWNWESTERN CAPE",
  "Cnr Tokai & Keyser River DriveTokaiCape Town",
  "32 ST JAMES STREET SOMERSET WEST 7130 021 852 5007",
  "KROMBOOM DENTAL CENTRE CNR KROMBROOM & BURWOOD ROAD, CRAWFORDCAPE TOWN",
  "PAARL FAMILY HEALTH 147 MAIN ROAD PAARL, 7646",
  "SUITE F1, BLOCK C ROCHESTER PLACE 173 RIVONIA ROAD MORNINGSIDE",
  "56 CHAMBERLAIN ROAD VINCENTEAST LONDONEASTERN CAPE",
  "Shop 43 Midway Shopping Centre Cnr Jan van Riebeeck & Wamkelekile StreetPaarlCape Town",
  "38 BOWWOOD ROAD CLAREMONTCAPE TOWNWESTERN CAPE",
  "1 Doring Ave Montana Park",
  "76 BONZA BAY ROAD BEACON BAYEAST LONDON",
  "THE COSMETIC & DENTAL EMPORIUM SHOP G28CAPE TOWNWESTERN CAPE",
  "CNR WITKOPPEN & STONEHAVEN RD, CAMBRIDGE CROSSING,JOHANNESBURGGAUTENG",
  "SUITE 6 FOUNTAIN MEDICAL CENTRE, 8A MURRAY SMITH ROAD,WINKLESPRUITKWAZULU-NATAL",
  "64 CHESTER STREET,BRYANSTONGAUTENG.",
  "2 SYCAMORE STREET, ZWARTKOP,CENTURIONGAUTENG",
  "20A KLOOF ROAD, SARLAN PARK CNR THE PARADE,Parktown NorthGauteng",
  "109 HIGH STREET MOSSEL BAY CENTRALMOSSEL BAYGEORGE",
  "DELIVERED ON YOUR BEHALF TO: SIBUYI BI INCORPORATED - SHOP NO 7PIETERHOF BUILDING",
  "11 12TH AVENUE PARKTOWN NORTHJOHANNESBURGGAUTENG",
  "13 HUDSON STREET,GREENPOINTCAPE TOWN",
  "577 RUBENSTEI DRIVE, MORELETA PARK,PRETORIA",
  "SHOP 18 CMA CENTRCHATSWORTH KZNKZN",
  "67 ROSEMEAD AVENUE, KENILWORTH,CAPE TOWNWESTERN CAPE",
  "155 GENERAL HERTZOG ROAD, THREE RIVERS,GAUTENG",
  "THE WELL CENTRE (SUITE 2) SUITE NO 2, 1ST FLOORBALLITOKWAZULU-NATAL",
  "FOR GEORGE: ORDERED BY JO MARI, 2 KNYSNA ROAD,LOERIE PARKGEORGE EAST",
  "Vat No: 4720225046 | 2A Schroder Street,UpingtonNorthern Cape",
  "101 PANORAMA SHOPPING CENTRE Hendrik Verwoerd Drive,PANORAMACAPE TOWN",
  "SHOP 14 1ST FLOOR, RINK HOUSE,PORT ELIZABETHEASTERN CAPE",
  "SUITE 120, SANDTON MEDICAL MEWS, SANDTON CITY SHOPPING CENTER,SANDTONGAUTENG",
  "Shop 2 8 Sandown RoadWest Beach TableviewCape Town",
  "234 ATHOL STREET, Highlands North,JohannesburgGauteng",
  "23 4TH AVENUE, MELLVILLE,JOHANNESBURGGAUTENG",
  "Cnr of Ethelbert & Conabar QueensburgMalvernDurban",
  "577 RUBENSTEIN DRIVE, MORELETA PARK,PRETORIAGAUTENG",
  "HOBDAY CRES NR 42 SILVERLAKESPRETORIAGAUTENG",
  "SHOP 18 RIVERSIDE SHOPPING CENTRE , BRYANSTON DRIVE ,SANDTONGAUTENG",
  "2998 WILLIAM NICOL DRIVE, NHC BRYANSTON,BYRANSTONGAUTENG",
  "DP 5 LA PRENEUSE APARTMENTS, LA PRENEUSE ROAD,BLACK RIVER",
  "Shop 8 Sentra Building CNR Gordons Bay Drive & Hammond StreetStrandCape Town",
  "Plot 2850, South Ring Road, X10,GaboroneSouth East",
  "DELIVERED ON YOUR BEHALF TO: DR THABELO MAGIDI -SHOP C4-DE WAAL STREET-ROSSLYN PLAZA",
  "24 Mose Tjitendero Street,OlympiaWindhoek",
  "SUITE 5, MY HEALT MEDICAL CENTRE 219 HOSSEN HAFFEJEE STREET (BERG)PIETERMARITZBURGKZN",
  "59494437, Allee Des Flamboyants,Carlos MorcellementTamarin Black River",
  "4 RAND STREET,VREDENDALWESTERN CAPE",
  "5 ASHSTEAD ROAD, GREEN POINT,CAPE TOWNWESTERN CAPE",
  "23 HARRY TRICHARD CRESCENT, CLAREY PARK ESTATE,BethelsdorpPORT ELIZABETH",
  "80 BEYERS NAUDE DRIVE NORTHCLIFFJOHANNESBURGGAUTENG",
  "30 MIMOSA STREET WILROPARK 1731",
  "28 de Clercq StreetErmelo",
  "113 VAN RENSBURG STREET PARKTOWN ESTATEPRETORIA",
  "52 FRASER STREET,HOWICKKWAZULU-NATAL",
  "VITAL DENT 41 STEYN VAN DER SPUY STREETSECUNDA -2302",
  "16 BOWWOOD ROAD, CLAREMONT,CAPE TOWNWESTERN CAPE",
  "HILL PARK BUILDING 49 HILL STREET CENTRAL,KROONSTADFree State",
  "SHOP 2, SHU HOUSE, NIELSON STREET,PORT ELIZABETHEASTERN CAPE",
  "KWAMNYANDU SHOPPING CENTRE, 341 V GRIFFITHS MXENGE HIGHWAY,UMLAZIKWA-ZULU NATAL",
  "Shop 3f Garden Centre Broadacres Shopping Centre, Cnr Cedar &, Valley Rd,Broadacres ParkJohannesburg",
  "SUITE C111 LENMED CLINICJOHANNESBURGGAUTENG",
  "56 4TH AVENUE, LAMBTON,GERMISTONGAUTENG",
  "11 12TH AVENUE, PARKTOWN NORTH,JOHANNESBURGGAUTENG",
  "Webber Rd & Oliver Street Estera Wadeville,GemistonGauteng",
  "36 MONTE CARLO CRESCENT, KYALAMI PARK,MIDRANDGAUTENG",
  "DENTISTS@HEALTH, 273 MAIN ROAD,WALMERPORT ELIZABETH",
  "SHOP 2 DTI CAMPUS, 11 ROBERT SOBUKWE STREET,SUNNYSIDEPRETORIA",
  "LOMBARDY BUSINESS PARK, UNIT 112,PRETORIAGAUTENG",
  "11 OCEAN WAY, SUNSET BEACH,CAPE TOWNWESTERN CAPE",
  "SHOP G28 WILLOWBRIDGE SHOPPING MALL, 39 CARL CRONJE AVENUE, BELLVILLE,CAPE TOWNWESTERN CAPE",
  "57 DURBAN STREET, CANNON HILL,UITENHAGE",
  "SUITE C1, GROUND FLOOR ABIA HOUSEABUJANIGERIA",
  "26 De Clercq Street,ErmeloMpumalanga",
  "41 STEYN VAN DER SPUY STREET,SECUNDA",
  "GATE 2 CNR BAKSTEEN & AXEL DRIVE, CLAYVILLE,OLIFANSFONTEINGAUTENG",
  "101 PANORAMA SHOPPING CENTRE, HENDRIK VERWOERD DRIVE,PANORAMACAPE TOWN",
  "254 MAIL ROAD, MALVERNE,QUEENSBURGHKWAZULU-NATAL",
  "MCC Shopping Centre, 1A Dora tamanew Street,Flamwood KlerksdorpNorth West",
  "DELIVERED ON YOUR BEHALF TO: DR YVETTE FRANCES SOLOMONS, SUITE A, MELROSE NORTH MEDICAL & DENTAL CARE82 CORLETT DRIVEMELROSE NORTH",
  "UNIT 6B, PLOT 54354,CENTRAL SQUAREGABARONE",
  "15 HELDERBERG ROAD, STUARTS HILL,CAPE TOWNWESTERN CAPE",
  "53 VOORTREKKER AVENUE, EDENVALE,JOHANNESBURGGAUTENG",
  "65 A Sutherland Street P.O. Box 77NewcastleKZN",
  "1st Floor Chiapani HouseGreenpointCape Town",
  "4 PARK LANE, CENTURY CITY GROUND FLOOR CENTURY MEDICAL SUITES,CAPE TOWNWESTERN CAPE",
  "SHOP 7B CNR OF FLORIN AND KRUGERARAND ROADSTUBENSVALLEYROODEPOORT",
  "SUITE 11, GROUND FLOOR, HIGHVELD SHOPPING CENTRE,HIGHVELDGAUTENG",
  "4 SIR LOWRY PASS,VredendalWestern Cape",
  "75, 12TH AVENUE,KENSINGTONMAITLAND",
  "293 RISSIK AVENUE BARCLAY SQUARE SHOPPING CENTER SUNNYSIDE 0002",
  "53 St, Albans Avenue Mayfair WestJohannesburgGAuteng",
  "103 Voortrekker Road,Maitland",
  "86B MARSH STREET, MOSS BAY CENTRAL,Mossel BayWestern Cape",
  "Registration No:2015/378797/07 | Shop 8, 100 Market Street,Polokwane",
  "710 TIPPERARY WAY, FAERIE GLEN,PRETORIA EAST",
  "20 OLYWENHOUT AVENUE BOSMONTJOHANNESBURGGAUTENG",
  "Shop 3f Garden Centre Broadacres Shopping Centre, Cnr Cedar &, Valley Rd,Broadacres ParkGauteng",
  "PAAREVLEI SPECIALIST MEDICAL CENTRE, 26 GARDNER WILLIAMS AVENUE, PAARDEVLEI,SOMMERSET WESTWESTERN CAPE",
  "86B MARSH STREET, MOSS BAY CENTRAL,MOSSEL BAY",
  "SHOP 4, GROENKLOOF PLAZA, C/O BAINES AND GEORGE,PRETORIAGAUTENG",
  "Stellen Road Freeway ParkBoksburgGauteng",
  "51 FAIRBAIRN STREET, WORCESTER,WORCESTERWESTERN CAPE",
  "VAAL DENTAL STUDIO, 155 GENERAL HERTZOG, THREE RIVERS,VEREENINGINGGAUTENG",
  "VAT No: 4090128267 151 Cape Road,151 Cape Road Mill ParkPort Elizabeth",
  "Kaapweg 151, 151 Cape Rd,Glendinningvale GqeberhaWestern Cape",
  "23 MEL MENTZ STREET,ERMELOMPUMALANGA",
  "86B MARSH STREET, MOSS BAY CENTRAL,MOSSEL BAYWESTERN CAPE",
  "166 Marone Street, EXT 5, Burgersfort,",
  "SHOP 271,THE GROVE MALL OF NAMIBIA CNR OF CHASIE & FRANKIE FREDERICKS STREETWINDHOEK",
  "72 11TH STREET, PARKMORE,JOHANNESBURGGAUTENG",
  "29 Cross Street, Kroonstad,",
  "N H C Health Centre, 207 Cnr Beyers Naude Drive,Northcliff JohannesburgGauteng",
  "45-47 CUYLER STREET CENTRAL UITENHAGEPORT ELIZABETH0",
  "99 Michelle Ave RandhartAlbertonGauteng",
  "SUITE A, MELROSE NORTH MEDICAL _AND_ DENTAL CENTREJOHANNESBURGGAUTENG",
  "310 ONTDEKKERS ROAD, ROODEPOORT,JOHANNESBURGGAUTENG",
  "Dentaville City Centre 56 Speke AveHarareZimbabwe",
  "VAT Number: 4090128267151 Cape Road Mill ParkPort Elizabeth",
  "SHOP 18 RIVERSIDE SHOPPING CENTRE , BRYANSTON DRIVE - BRYANSTON, SANDTON, GAUTENG,VAT 4950274672",
  "154 KLOOF STREET ORANJEZICHTCAPE TOWNWESTERN CAPE",
  "ADVANCED GROENKLOOF DAY HOSP. GEBOU 2, SUITE 2PRETORIAGAUTENG",
  "11 HARTSHORNE STREET RYNFIELDJOHANNESBURGGAUTENG",
  "49 HILL STREET,KROONSTADFREE STATE",
  "14 Huilboom Street, Moreletapark,PretoriaGauteng",
  "DR PHILIP JONSSON, BLOCK 1, 2ND FLOOR, SUITE 205, MEDICLINIC.VERGELEGEN MAIN ROAD SOMERSET WESTCAPE TOWN",
  "39 KLOOF STREET, GARDENS,CAPE TOWNWESTERN CAPE",
  "Atterbury Boulevard, Atterbury Rd, Faerie Glen,PretoriaGauteng",
  "11 Louise Street, Del Judor,Witbank",
  "Shop No 1, South Way Mall, 27 Triten Road,Sea ViewDurban South",
  "39 Carl Cronje Dr #G2Cape Town",
  "Medicross Saxby, 1053 Frederik Ave,Eldoraigne CenturionGauteng",
  "DP5 LO PRENEUSE APARTMENTS LA PRENEUSE ROADBLACK RIVER",
  "95 BRAM FISCHER DRIVE, FERNDALE,RandburgGauteng",
  "996F Stugulukile Centre, R573 Moloto Road,KwamhlangaMpumalanga",
  "THE DIRECTOR OF FINANCE PRIVATE BAG X 20HatfieldGauteng",
  "51 Albertyn Street, Vorna Valley,MidrandGauteng",
  "189 SEFAKO MAKGATHO DRIVE SINOVILLE 0182 012 548 3381 / 082 779 0335",
  "Primrose Dental Practice 26 Petunia RoadGermiston",
  "310 Ondekkers Road, Roodepoort,JohannesburgGauteng",
  "1020 Saxby Avenue, Eldoraigne,CenturionGauteng",
  "29 Mulders Mile, Eldoraigne,CenturionGauteng",
  "117 Ventersdorp Rd, Brandvlei,RandfonteinGauteng",
  "123,11th STREET PARKMOREJOHANNESBURGGAUTENG",
  "The Well Medical & Dental Centre, Suite 2, Kirsty Close,BallitoKwa-Zulu Natal",
  "75 12th Ave, Kensington,Cape TownWestern Cape",
  "Vat No: 4870298538 | The Well Medical & Dental Centre,Suite 2, Kirsty Close,BallitoKwa-Zulu Natal",
  "Shop 16, Mulbarton Shopping Centre,GlenvistaJohannesburg",
  "32 Dr. Beyers Naude Street,MiddelburgMpumalanga",
  "DELIVERED ON YOUR BEHALF TO: DR LEBOGANG DINEO NAPE MOTSHANA EMALAHLENI PRIVATE HOSPITAL SUITE 219A, 39 MANDELA DRIVE EMALAHLENI 1034EmalahleniGauteng",
  "55 HOMESTEAD AVE BRYNASTON 2191",
  "CLEAR SMILE DENTAL CARE NTUANE EATING HOUSENGWABELIMPOPO",
  "15 HELDERBERG ROAD STUARTS HILLCAPE TOWNWESTERN CAPE",
  "DARBY MANSIONS 436 BRICKFIELD ROADBEREAKZN",
  "24 MOSE TJITENDERO STREET OLYMPIAWINDHOEKNAMIBIA",
  "577 RUBENSTEIN DRIVE MORELETA PARKPRETORIAGAUTENG",
  "MARAKANELO WAY UNIT EBOTSWANABOTSWANA",
  "1ST FLOOR BROOKLYN DENTAL CENTREPRETORIAGAUTENG",
  "SHOP 33 KYALAMI ON MAIN SHOPPING CENTREJOHANNESBURGGAUTENG",
  "NO 9 SHASONS CENTRE CNR WARREN AND_SHIPPARD STRMAFIKENGNORTH WEST",
  "15 ON ORANGE HOTEL UNIT 19 CORNER OF ORANGE STREETCAPE TOWNWESTERN CAPE",
  "C/O JJ HADEBE AND NIEUW STREET FRAKNKFORTFRANKFORTFREE STATE",
  "DELIVERED ON YOUR BEHALF TO: 0",
  "SCHOOL OF ORAL HEALTH SCIENCES MEDUNSA ORAL,PRETORIAGAUTENG",
  "N H C Health Centre 207 Cnr Beyers Naude Drive _AND_JOHANNESBURGGAUTENG",
  "MEDICLINIC MIDSTREAM SUITE 117PRETORIAGAUTENG",
  "37c CARRINGTON STREET 0MAHIKENGVAT NO: 4920169952",
  "NEW REDRUTH ALBERTONALBERTONGAUTENG",
  "32 ST JAMES STREET SOMERSET WESTCAPE TOWNWESTERN CAPE",
  "155 GENL HERTZOG STREET THREE RIVERSVEREENIGING0",
  "THE DIRECTOR OF FINANCE PRIVATE BAG X 20HATFIELDGAUTENG",
  "CORNELIUS STREET WELTEVREDENPARKROODEPOORTGAUTENG",
  "CAMPS BAY DENTAL STUDIO 49 VICTORIA ROADCAPE TOWNWESTERN CAPE",
  "SHOP 4, GROENKLOOF PLAZA C/O BAINES _AND_ GEORGEPRETORIAGAUTENG",
  "CNR ANNETTE VAN ZYL AND JAQUELINE STREETPRETORIAGAUTENG",
  "13 HUDSON STREET GREENPOINTCAPE TOWNWESTERN CAPE",
  "SHOP 45A SCOTTSBURGH MALL",
  "7 CAMPBELL DRIVE SUITE 2CORALS ON CAMPBELLKZN",
  "CNR WITKOPPEN _AND_ STONEHAVEN RD, CAMBRIDGEJOHANNESBURGGAUTENG",
  "PRETORIA GAUTENGPRETORIAGAUTENG",
  "108 GRANADA SQUARE 16 CHARTWELL DRIVE",
  "16 BOWWOOD ROAD CLAREMONTCAPE TOWNWESTERN CAPE",
  "LOMBARDY BUSINESS PARK UNIT 112PRETORIAGAUTENG",
  "28 BOLTON ROAD, CNR BATH ROSEBANKJOHANNESBURGGAUTENG",
  "KILNER PARK CLINIC 255 ANNA WILSON STREETPRETORIAGAUTENG",
  "4 PARK LANE, CENTURY CITY GROUND FLOORCAPE TOWNWESTERN CAPE",
  "ROOM 733 7TH FLOOR LOUIS PASTEUR PRIVATE HOSPITALPRETORIAGAUTENG",
  "2 PALMERTON ROAD LONEHILL DENTAL EXCELLENCE LONEHILL 2191PRETORIAGAUTENG",
  "93 GLENWOOD STREET LYNNWOOD GLEN PRETORIA 084 986 0005PRETORIAGAUTENG",
  "3 DOCK ROAD WATERWAY HOUSECAPE TOWNWESTERN CAPE",
  "67 ROSEMEAD AVENUE KENILWORTH 7800CAPE TOWNWESTERN CAPE",
  "52 MARONE STREET BURGERSFORT",
  "16-18 GARDNER WILLIAMS AVENUE",
  "NHC CENTURION CNR BRAKFONTEIN",
  "FACULTY OF HEALTH SCIENCES LEVEL 4JOHANNESBURGGAUTENG",
  "PLOT 64516. UNIT 105GABARONEBOTSWANA",
  "ROOM 207 SECUNDA MEDFORUM BLD CHRIS HEUNIS STREET SECUNDA 2302 017 634 1797",
  "MILITARY HEALTH PROC UNIT PRIVATE BAG X102 CENTURION 0046",
  "GEORGE",
  "SHOP 3F, GARDEN COURT BROADACRES SHOPPING CENTREJOHANNESBURGGAUTENG",
  "13 HUDSON STREET GREENPOINT CAPE TOWN 8001",
  "36 Monte Carlo Crescent Kyalami ParkMidrandGauteng",
  "DP0065854 131a CURRIE ROAD MUSGRAVE - 4001 051 451 1106DurbanKwaZulu-Natal",
  "55 BERGVLIETBERGVLIETCAPE TOWN",
  "16 BOWWOOD ROAD CLAREMONT CAPE TOWN",
  "9 TARENTAAL STREET CNR FLAMINGO STREET SEDGEFIELD 6573",
  "DELIVERED ON YOUR BEHALF TO: 0PRETORIAGAUTENG",
  "230 SIDNEY AVE WATERKLOOFPRETORIAGAUTENG",
  "DR NIKHAEL TULARAM 55 HINTON GROVEVIRGINIADURBAN",
  "Jan Smuts Ave &, 6th Rd, Hyde Park, Sandton, 2196",
  "DELIVERED ON YOUR BEHALF TO: MCGYVER DENTAL 24 (PTY) LTD31 CORNWELL STREET - OAKDALEBELLVILLE -",
  "SUITE 6 FOUNTAIN MEDICAL CENTRE8A MURRAY SMITH ROAD - WINKELSPRUIT -KWA ZULU NATAL",
  "Suite 117 First Floor, Hyde Park Corner,JohannesburgGauteng",
  "NONE NONENONENONE",
];


export default router;
